/*
 * This file is generated by jOOQ.
 */
package com.svnlan.jooq.tables.records;


import com.svnlan.jooq.tables.CommonDesign;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 页面编辑器表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommonDesignRecord extends UpdatableRecordImpl<CommonDesignRecord> {

    private static final long serialVersionUID = 680219677;

    /**
     * Setter for <code>cloud_disk.common_design.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>cloud_disk.common_design.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>cloud_disk.common_design.title</code>. 名称
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cloud_disk.common_design.title</code>. 名称
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cloud_disk.common_design.offset</code>. 偏移量，坐标{x,y}
     */
    public void setOffset(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>cloud_disk.common_design.offset</code>. 偏移量，坐标{x,y}
     */
    public String getOffset() {
        return (String) get(2);
    }

    /**
     * Setter for <code>cloud_disk.common_design.size</code>. 尺寸大小，长宽{length,height}
     */
    public void setSize(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>cloud_disk.common_design.size</code>. 尺寸大小，长宽{length,height}
     */
    public String getSize() {
        return (String) get(3);
    }

    /**
     * Setter for <code>cloud_disk.common_design.pic</code>. 缩略图，文件id
     */
    public void setPic(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>cloud_disk.common_design.pic</code>. 缩略图，文件id
     */
    public Long getPic() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>cloud_disk.common_design.gmt_create</code>. 创建时间
     */
    public void setGmtCreate(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>cloud_disk.common_design.gmt_create</code>. 创建时间
     */
    public LocalDateTime getGmtCreate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>cloud_disk.common_design.gmt_modified</code>. 修改时间
     */
    public void setGmtModified(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>cloud_disk.common_design.gmt_modified</code>. 修改时间
     */
    public LocalDateTime getGmtModified() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>cloud_disk.common_design.detail</code>. 页面内容
     */
    public void setDetail(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>cloud_disk.common_design.detail</code>. 页面内容
     */
    public String getDetail() {
        return (String) get(7);
    }

    /**
     * Setter for <code>cloud_disk.common_design.design_type</code>. 编辑器类型类型，1主页，2二级页
     */
    public void setDesignType(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>cloud_disk.common_design.design_type</code>. 编辑器类型类型，1主页，2二级页
     */
    public String getDesignType() {
        return (String) get(8);
    }

    /**
     * Setter for <code>cloud_disk.common_design.client_type</code>. 客户端类型，1PC，2手机端，3APP，4小程序
     */
    public void setClientType(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>cloud_disk.common_design.client_type</code>. 客户端类型，1PC，2手机端，3APP，4小程序
     */
    public String getClientType() {
        return (String) get(9);
    }

    /**
     * Setter for <code>cloud_disk.common_design.is_used</code>. 标识是否当前使用中的设置，是或否
     */
    public void setIsUsed(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>cloud_disk.common_design.is_used</code>. 标识是否当前使用中的设置，是或否
     */
    public Integer getIsUsed() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>cloud_disk.common_design.url</code>. 客户端访问路径，网校域名
     */
    public void setUrl(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>cloud_disk.common_design.url</code>. 客户端访问路径，网校域名
     */
    public String getUrl() {
        return (String) get(11);
    }

    /**
     * Setter for <code>cloud_disk.common_design.file_url</code>. 文件存放路径
     */
    public void setFileUrl(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>cloud_disk.common_design.file_url</code>. 文件存放路径
     */
    public String getFileUrl() {
        return (String) get(12);
    }

    /**
     * Setter for <code>cloud_disk.common_design.fk_common_design_id</code>. 编辑器id，用于二级页面
     */
    public void setFkCommonDesignId(Long value) {
        set(13, value);
    }

    /**
     * Getter for <code>cloud_disk.common_design.fk_common_design_id</code>. 编辑器id，用于二级页面
     */
    public Long getFkCommonDesignId() {
        return (Long) get(13);
    }

    /**
     * Setter for <code>cloud_disk.common_design.foot</code>. 底部
     */
    public void setFoot(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>cloud_disk.common_design.foot</code>. 底部
     */
    public String getFoot() {
        return (String) get(14);
    }

    /**
     * Setter for <code>cloud_disk.common_design.head</code>. 头部
     */
    public void setHead(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>cloud_disk.common_design.head</code>. 头部
     */
    public String getHead() {
        return (String) get(15);
    }

    /**
     * Setter for <code>cloud_disk.common_design.setting</code>. 样式设置
     */
    public void setSetting(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>cloud_disk.common_design.setting</code>. 样式设置
     */
    public String getSetting() {
        return (String) get(16);
    }

    /**
     * Setter for <code>cloud_disk.common_design.applet</code>. 小程序的配置信息
     */
    public void setApplet(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>cloud_disk.common_design.applet</code>. 小程序的配置信息
     */
    public String getApplet() {
        return (String) get(17);
    }

    /**
     * Setter for <code>cloud_disk.common_design.source_design_id</code>. 来源装扮id
     */
    public void setSourceDesignId(Long value) {
        set(18, value);
    }

    /**
     * Getter for <code>cloud_disk.common_design.source_design_id</code>. 来源装扮id
     */
    public Long getSourceDesignId() {
        return (Long) get(18);
    }

    /**
     * Setter for <code>cloud_disk.common_design.approval_state</code>. 审核状态，0待审核，1通过，2不通过
     */
    public void setApprovalState(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>cloud_disk.common_design.approval_state</code>. 审核状态，0待审核，1通过，2不通过
     */
    public String getApprovalState() {
        return (String) get(19);
    }

    /**
     * Setter for <code>cloud_disk.common_design.approval_detail</code>. 审核备注
     */
    public void setApprovalDetail(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>cloud_disk.common_design.approval_detail</code>. 审核备注
     */
    public String getApprovalDetail() {
        return (String) get(20);
    }

    /**
     * Setter for <code>cloud_disk.common_design.gmt_approval</code>. 审核时间
     */
    public void setGmtApproval(LocalDateTime value) {
        set(21, value);
    }

    /**
     * Getter for <code>cloud_disk.common_design.gmt_approval</code>. 审核时间
     */
    public LocalDateTime getGmtApproval() {
        return (LocalDateTime) get(21);
    }

    /**
     * Setter for <code>cloud_disk.common_design.sort</code>. 排序字段
     */
    public void setSort(Integer value) {
        set(22, value);
    }

    /**
     * Getter for <code>cloud_disk.common_design.sort</code>. 排序字段
     */
    public Integer getSort() {
        return (Integer) get(22);
    }

    /**
     * Setter for <code>cloud_disk.common_design.state</code>. 状态
     */
    public void setState(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>cloud_disk.common_design.state</code>. 状态
     */
    public String getState() {
        return (String) get(23);
    }

    /**
     * Setter for <code>cloud_disk.common_design.is_paste</code>. 是否复制
     */
    public void setIsPaste(Integer value) {
        set(24, value);
    }

    /**
     * Getter for <code>cloud_disk.common_design.is_paste</code>. 是否复制
     */
    public Integer getIsPaste() {
        return (Integer) get(24);
    }

    /**
     * Setter for <code>cloud_disk.common_design.seo</code>. seo. keyword, description的json
     */
    public void setSeo(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>cloud_disk.common_design.seo</code>. seo. keyword, description的json
     */
    public String getSeo() {
        return (String) get(25);
    }

    /**
     * Setter for <code>cloud_disk.common_design.mb_design_id</code>. 关联h5编辑器ID
     */
    public void setMbDesignId(Long value) {
        set(26, value);
    }

    /**
     * Getter for <code>cloud_disk.common_design.mb_design_id</code>. 关联h5编辑器ID
     */
    public Long getMbDesignId() {
        return (Long) get(26);
    }

    /**
     * Setter for <code>cloud_disk.common_design.design_classify_id</code>. 装扮分类id
     */
    public void setDesignClassifyId(Integer value) {
        set(27, value);
    }

    /**
     * Getter for <code>cloud_disk.common_design.design_classify_id</code>. 装扮分类id
     */
    public Integer getDesignClassifyId() {
        return (Integer) get(27);
    }

    /**
     * Setter for <code>cloud_disk.common_design.path_pre</code>. 路径前缀
     */
    public void setPathPre(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>cloud_disk.common_design.path_pre</code>. 路径前缀
     */
    public String getPathPre() {
        return (String) get(28);
    }

    /**
     * Setter for <code>cloud_disk.common_design.tenant_id</code>. 租户id
     */
    public void setTenantId(Long value) {
        set(29, value);
    }

    /**
     * Getter for <code>cloud_disk.common_design.tenant_id</code>. 租户id
     */
    public Long getTenantId() {
        return (Long) get(29);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CommonDesignRecord
     */
    public CommonDesignRecord() {
        super(CommonDesign.COMMON_DESIGN);
    }

    /**
     * Create a detached, initialised CommonDesignRecord
     */
    public CommonDesignRecord(Long id, String title, String offset, String size, Long pic, LocalDateTime gmtCreate, LocalDateTime gmtModified, String detail, String designType, String clientType, Integer isUsed, String url, String fileUrl, Long fkCommonDesignId, String foot, String head, String setting, String applet, Long sourceDesignId, String approvalState, String approvalDetail, LocalDateTime gmtApproval, Integer sort, String state, Integer isPaste, String seo, Long mbDesignId, Integer designClassifyId, String pathPre, Long tenantId) {
        super(CommonDesign.COMMON_DESIGN);

        set(0, id);
        set(1, title);
        set(2, offset);
        set(3, size);
        set(4, pic);
        set(5, gmtCreate);
        set(6, gmtModified);
        set(7, detail);
        set(8, designType);
        set(9, clientType);
        set(10, isUsed);
        set(11, url);
        set(12, fileUrl);
        set(13, fkCommonDesignId);
        set(14, foot);
        set(15, head);
        set(16, setting);
        set(17, applet);
        set(18, sourceDesignId);
        set(19, approvalState);
        set(20, approvalDetail);
        set(21, gmtApproval);
        set(22, sort);
        set(23, state);
        set(24, isPaste);
        set(25, seo);
        set(26, mbDesignId);
        set(27, designClassifyId);
        set(28, pathPre);
        set(29, tenantId);
    }
}
