/*
 * This file is generated by jOOQ.
 */
package com.svnlan.jooq.tables.records;


import com.svnlan.jooq.tables.IoFileContents;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 文件id
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IoFileContentsRecord extends UpdatableRecordImpl<IoFileContentsRecord> implements Record4<Long, String, LocalDateTime, Long> {

    private static final long serialVersionUID = 108312514;

    /**
     * Setter for <code>cloud_disk.io_file_contents.file_id</code>.
     */
    public void setFileId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>cloud_disk.io_file_contents.file_id</code>.
     */
    public Long getFileId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>cloud_disk.io_file_contents.content</code>. 文本文件内容,最大16M
     */
    public void setContent(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cloud_disk.io_file_contents.content</code>. 文本文件内容,最大16M
     */
    public String getContent() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cloud_disk.io_file_contents.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>cloud_disk.io_file_contents.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>cloud_disk.io_file_contents.tenant_id</code>. 租户id
     */
    public void setTenantId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>cloud_disk.io_file_contents.tenant_id</code>. 租户id
     */
    public Long getTenantId() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, LocalDateTime, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, String, LocalDateTime, Long> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return IoFileContents.IO_FILE_CONTENTS.FILE_ID;
    }

    @Override
    public Field<String> field2() {
        return IoFileContents.IO_FILE_CONTENTS.CONTENT;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return IoFileContents.IO_FILE_CONTENTS.CREATE_TIME;
    }

    @Override
    public Field<Long> field4() {
        return IoFileContents.IO_FILE_CONTENTS.TENANT_ID;
    }

    @Override
    public Long component1() {
        return getFileId();
    }

    @Override
    public String component2() {
        return getContent();
    }

    @Override
    public LocalDateTime component3() {
        return getCreateTime();
    }

    @Override
    public Long component4() {
        return getTenantId();
    }

    @Override
    public Long value1() {
        return getFileId();
    }

    @Override
    public String value2() {
        return getContent();
    }

    @Override
    public LocalDateTime value3() {
        return getCreateTime();
    }

    @Override
    public Long value4() {
        return getTenantId();
    }

    @Override
    public IoFileContentsRecord value1(Long value) {
        setFileId(value);
        return this;
    }

    @Override
    public IoFileContentsRecord value2(String value) {
        setContent(value);
        return this;
    }

    @Override
    public IoFileContentsRecord value3(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public IoFileContentsRecord value4(Long value) {
        setTenantId(value);
        return this;
    }

    @Override
    public IoFileContentsRecord values(Long value1, String value2, LocalDateTime value3, Long value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IoFileContentsRecord
     */
    public IoFileContentsRecord() {
        super(IoFileContents.IO_FILE_CONTENTS);
    }

    /**
     * Create a detached, initialised IoFileContentsRecord
     */
    public IoFileContentsRecord(Long fileId, String content, LocalDateTime createTime, Long tenantId) {
        super(IoFileContents.IO_FILE_CONTENTS);

        set(0, fileId);
        set(1, content);
        set(2, createTime);
        set(3, tenantId);
    }
}
