/*
 * This file is generated by jOOQ.
 */
package com.svnlan.jooq.tables.records;


import com.svnlan.jooq.tables.IoSourceEvent;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 文档事件表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IoSourceEventRecord extends UpdatableRecordImpl<IoSourceEventRecord> implements Record8<Long, Long, Long, Long, String, String, LocalDateTime, Long> {

    private static final long serialVersionUID = 596196927;

    /**
     * Setter for <code>cloud_disk.io_source_event.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>cloud_disk.io_source_event.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>cloud_disk.io_source_event.source_id</code>. 文档id
     */
    public void setSourceId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>cloud_disk.io_source_event.source_id</code>. 文档id
     */
    public Long getSourceId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>cloud_disk.io_source_event.source_parent</code>. 文档父文件夹id
     */
    public void setSourceParent(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>cloud_disk.io_source_event.source_parent</code>. 文档父文件夹id
     */
    public Long getSourceParent() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>cloud_disk.io_source_event.user_id</code>. 操作者id
     */
    public void setUserId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>cloud_disk.io_source_event.user_id</code>. 操作者id
     */
    public Long getUserId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>cloud_disk.io_source_event.type</code>. 事件类型
     */
    public void setType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>cloud_disk.io_source_event.type</code>. 事件类型
     */
    public String getType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>cloud_disk.io_source_event.detail</code>. 数据详情，根据type内容意义不同
     */
    public void setDetail(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>cloud_disk.io_source_event.detail</code>. 数据详情，根据type内容意义不同
     */
    public String getDetail() {
        return (String) get(5);
    }

    /**
     * Setter for <code>cloud_disk.io_source_event.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>cloud_disk.io_source_event.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>cloud_disk.io_source_event.tenant_id</code>. 租户id
     */
    public void setTenantId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>cloud_disk.io_source_event.tenant_id</code>. 租户id
     */
    public Long getTenantId() {
        return (Long) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, Long, Long, Long, String, String, LocalDateTime, Long> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, Long, Long, Long, String, String, LocalDateTime, Long> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return IoSourceEvent.IO_SOURCE_EVENT.ID;
    }

    @Override
    public Field<Long> field2() {
        return IoSourceEvent.IO_SOURCE_EVENT.SOURCE_ID;
    }

    @Override
    public Field<Long> field3() {
        return IoSourceEvent.IO_SOURCE_EVENT.SOURCE_PARENT;
    }

    @Override
    public Field<Long> field4() {
        return IoSourceEvent.IO_SOURCE_EVENT.USER_ID;
    }

    @Override
    public Field<String> field5() {
        return IoSourceEvent.IO_SOURCE_EVENT.TYPE;
    }

    @Override
    public Field<String> field6() {
        return IoSourceEvent.IO_SOURCE_EVENT.DETAIL;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return IoSourceEvent.IO_SOURCE_EVENT.CREATE_TIME;
    }

    @Override
    public Field<Long> field8() {
        return IoSourceEvent.IO_SOURCE_EVENT.TENANT_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getSourceId();
    }

    @Override
    public Long component3() {
        return getSourceParent();
    }

    @Override
    public Long component4() {
        return getUserId();
    }

    @Override
    public String component5() {
        return getType();
    }

    @Override
    public String component6() {
        return getDetail();
    }

    @Override
    public LocalDateTime component7() {
        return getCreateTime();
    }

    @Override
    public Long component8() {
        return getTenantId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getSourceId();
    }

    @Override
    public Long value3() {
        return getSourceParent();
    }

    @Override
    public Long value4() {
        return getUserId();
    }

    @Override
    public String value5() {
        return getType();
    }

    @Override
    public String value6() {
        return getDetail();
    }

    @Override
    public LocalDateTime value7() {
        return getCreateTime();
    }

    @Override
    public Long value8() {
        return getTenantId();
    }

    @Override
    public IoSourceEventRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public IoSourceEventRecord value2(Long value) {
        setSourceId(value);
        return this;
    }

    @Override
    public IoSourceEventRecord value3(Long value) {
        setSourceParent(value);
        return this;
    }

    @Override
    public IoSourceEventRecord value4(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public IoSourceEventRecord value5(String value) {
        setType(value);
        return this;
    }

    @Override
    public IoSourceEventRecord value6(String value) {
        setDetail(value);
        return this;
    }

    @Override
    public IoSourceEventRecord value7(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public IoSourceEventRecord value8(Long value) {
        setTenantId(value);
        return this;
    }

    @Override
    public IoSourceEventRecord values(Long value1, Long value2, Long value3, Long value4, String value5, String value6, LocalDateTime value7, Long value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IoSourceEventRecord
     */
    public IoSourceEventRecord() {
        super(IoSourceEvent.IO_SOURCE_EVENT);
    }

    /**
     * Create a detached, initialised IoSourceEventRecord
     */
    public IoSourceEventRecord(Long id, Long sourceId, Long sourceParent, Long userId, String type, String detail, LocalDateTime createTime, Long tenantId) {
        super(IoSourceEvent.IO_SOURCE_EVENT);

        set(0, id);
        set(1, sourceId);
        set(2, sourceParent);
        set(3, userId);
        set(4, type);
        set(5, detail);
        set(6, createTime);
        set(7, tenantId);
    }
}
