/*
 * This file is generated by jOOQ.
 */
package com.svnlan.jooq.tables.records;


import com.svnlan.jooq.tables.SystemLog;

import java.time.LocalDateTime;
import java.util.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 系统日志表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SystemLogRecord extends UpdatableRecordImpl<SystemLogRecord> implements Record10<Long, String, Long, String, String, Date, String, String, LocalDateTime, Long> {

    private static final long serialVersionUID = -979392875;

    /**
     * Setter for <code>cloud_disk.system_log.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>cloud_disk.system_log.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>cloud_disk.system_log.session_id</code>. session识别码，用于登陆时记录ip,UA等信息
     */
    public void setSessionId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cloud_disk.system_log.session_id</code>. session识别码，用于登陆时记录ip,UA等信息
     */
    public String getSessionId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cloud_disk.system_log.user_id</code>. 用户id
     */
    public void setUserId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>cloud_disk.system_log.user_id</code>. 用户id
     */
    public Long getUserId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>cloud_disk.system_log.type</code>. 日志类型
     */
    public void setType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>cloud_disk.system_log.type</code>. 日志类型
     */
    public String getType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>cloud_disk.system_log.detail</code>. 详情
     */
    public void setDetail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>cloud_disk.system_log.detail</code>. 详情
     */
    public String getDetail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>cloud_disk.system_log.visit_date</code>. 日期
     */
    public void setVisitDate(Date value) {
        set(5, value);
    }

    /**
     * Getter for <code>cloud_disk.system_log.visit_date</code>. 日期
     */
    public Date getVisitDate() {
        return (Date) get(5);
    }

    /**
     * Setter for <code>cloud_disk.system_log.client_type</code>. 1pc , 2h5, 3安卓app, 4 ios-app, 5小程序
     */
    public void setClientType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>cloud_disk.system_log.client_type</code>. 1pc , 2h5, 3安卓app, 4 ios-app, 5小程序
     */
    public String getClientType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>cloud_disk.system_log.os_name</code>. 操作系统
     */
    public void setOsName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>cloud_disk.system_log.os_name</code>. 操作系统
     */
    public String getOsName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>cloud_disk.system_log.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>cloud_disk.system_log.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>cloud_disk.system_log.tenant_id</code>. 租户id
     */
    public void setTenantId(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>cloud_disk.system_log.tenant_id</code>. 租户id
     */
    public Long getTenantId() {
        return (Long) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, String, Long, String, String, Date, String, String, LocalDateTime, Long> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, String, Long, String, String, Date, String, String, LocalDateTime, Long> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SystemLog.SYSTEM_LOG.ID;
    }

    @Override
    public Field<String> field2() {
        return SystemLog.SYSTEM_LOG.SESSION_ID;
    }

    @Override
    public Field<Long> field3() {
        return SystemLog.SYSTEM_LOG.USER_ID;
    }

    @Override
    public Field<String> field4() {
        return SystemLog.SYSTEM_LOG.TYPE;
    }

    @Override
    public Field<String> field5() {
        return SystemLog.SYSTEM_LOG.DETAIL;
    }

    @Override
    public Field<Date> field6() {
        return SystemLog.SYSTEM_LOG.VISIT_DATE;
    }

    @Override
    public Field<String> field7() {
        return SystemLog.SYSTEM_LOG.CLIENT_TYPE;
    }

    @Override
    public Field<String> field8() {
        return SystemLog.SYSTEM_LOG.OS_NAME;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return SystemLog.SYSTEM_LOG.CREATE_TIME;
    }

    @Override
    public Field<Long> field10() {
        return SystemLog.SYSTEM_LOG.TENANT_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getSessionId();
    }

    @Override
    public Long component3() {
        return getUserId();
    }

    @Override
    public String component4() {
        return getType();
    }

    @Override
    public String component5() {
        return getDetail();
    }

    @Override
    public Date component6() {
        return getVisitDate();
    }

    @Override
    public String component7() {
        return getClientType();
    }

    @Override
    public String component8() {
        return getOsName();
    }

    @Override
    public LocalDateTime component9() {
        return getCreateTime();
    }

    @Override
    public Long component10() {
        return getTenantId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getSessionId();
    }

    @Override
    public Long value3() {
        return getUserId();
    }

    @Override
    public String value4() {
        return getType();
    }

    @Override
    public String value5() {
        return getDetail();
    }

    @Override
    public Date value6() {
        return getVisitDate();
    }

    @Override
    public String value7() {
        return getClientType();
    }

    @Override
    public String value8() {
        return getOsName();
    }

    @Override
    public LocalDateTime value9() {
        return getCreateTime();
    }

    @Override
    public Long value10() {
        return getTenantId();
    }

    @Override
    public SystemLogRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SystemLogRecord value2(String value) {
        setSessionId(value);
        return this;
    }

    @Override
    public SystemLogRecord value3(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public SystemLogRecord value4(String value) {
        setType(value);
        return this;
    }

    @Override
    public SystemLogRecord value5(String value) {
        setDetail(value);
        return this;
    }

    @Override
    public SystemLogRecord value6(Date value) {
        setVisitDate(value);
        return this;
    }

    @Override
    public SystemLogRecord value7(String value) {
        setClientType(value);
        return this;
    }

    @Override
    public SystemLogRecord value8(String value) {
        setOsName(value);
        return this;
    }

    @Override
    public SystemLogRecord value9(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public SystemLogRecord value10(Long value) {
        setTenantId(value);
        return this;
    }

    @Override
    public SystemLogRecord values(Long value1, String value2, Long value3, String value4, String value5, Date value6, String value7, String value8, LocalDateTime value9, Long value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SystemLogRecord
     */
    public SystemLogRecord() {
        super(SystemLog.SYSTEM_LOG);
    }

    /**
     * Create a detached, initialised SystemLogRecord
     */
    public SystemLogRecord(Long id, String sessionId, Long userId, String type, String detail, Date visitDate, String clientType, String osName, LocalDateTime createTime, Long tenantId) {
        super(SystemLog.SYSTEM_LOG);

        set(0, id);
        set(1, sessionId);
        set(2, userId);
        set(3, type);
        set(4, detail);
        set(5, visitDate);
        set(6, clientType);
        set(7, osName);
        set(8, createTime);
        set(9, tenantId);
    }
}
