/*
 * This file is generated by jOOQ.
 */
package com.svnlan.jooq.tables.records;


import com.svnlan.jooq.tables.SystemOption;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 系统配置表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SystemOptionRecord extends UpdatableRecordImpl<SystemOptionRecord> implements Record7<Integer, String, String, String, LocalDateTime, LocalDateTime, Long> {

    private static final long serialVersionUID = 940336643;

    /**
     * Setter for <code>cloud_disk.system_option.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>cloud_disk.system_option.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>cloud_disk.system_option.type</code>. 配置类型
     */
    public void setType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cloud_disk.system_option.type</code>. 配置类型
     */
    public String getType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cloud_disk.system_option.key_string</code>.
     */
    public void setKeyString(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>cloud_disk.system_option.key_string</code>.
     */
    public String getKeyString() {
        return (String) get(2);
    }

    /**
     * Setter for <code>cloud_disk.system_option.value_text</code>.
     */
    public void setValueText(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>cloud_disk.system_option.value_text</code>.
     */
    public String getValueText() {
        return (String) get(3);
    }

    /**
     * Setter for <code>cloud_disk.system_option.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>cloud_disk.system_option.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>cloud_disk.system_option.modify_time</code>. 最后更新时间
     */
    public void setModifyTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>cloud_disk.system_option.modify_time</code>. 最后更新时间
     */
    public LocalDateTime getModifyTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>cloud_disk.system_option.tenant_id</code>. 租户id
     */
    public void setTenantId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>cloud_disk.system_option.tenant_id</code>. 租户id
     */
    public Long getTenantId() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, String, LocalDateTime, LocalDateTime, Long> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, String, String, LocalDateTime, LocalDateTime, Long> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return SystemOption.SYSTEM_OPTION.ID;
    }

    @Override
    public Field<String> field2() {
        return SystemOption.SYSTEM_OPTION.TYPE;
    }

    @Override
    public Field<String> field3() {
        return SystemOption.SYSTEM_OPTION.KEY_STRING;
    }

    @Override
    public Field<String> field4() {
        return SystemOption.SYSTEM_OPTION.VALUE_TEXT;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return SystemOption.SYSTEM_OPTION.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return SystemOption.SYSTEM_OPTION.MODIFY_TIME;
    }

    @Override
    public Field<Long> field7() {
        return SystemOption.SYSTEM_OPTION.TENANT_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getType();
    }

    @Override
    public String component3() {
        return getKeyString();
    }

    @Override
    public String component4() {
        return getValueText();
    }

    @Override
    public LocalDateTime component5() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component6() {
        return getModifyTime();
    }

    @Override
    public Long component7() {
        return getTenantId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getType();
    }

    @Override
    public String value3() {
        return getKeyString();
    }

    @Override
    public String value4() {
        return getValueText();
    }

    @Override
    public LocalDateTime value5() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value6() {
        return getModifyTime();
    }

    @Override
    public Long value7() {
        return getTenantId();
    }

    @Override
    public SystemOptionRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public SystemOptionRecord value2(String value) {
        setType(value);
        return this;
    }

    @Override
    public SystemOptionRecord value3(String value) {
        setKeyString(value);
        return this;
    }

    @Override
    public SystemOptionRecord value4(String value) {
        setValueText(value);
        return this;
    }

    @Override
    public SystemOptionRecord value5(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public SystemOptionRecord value6(LocalDateTime value) {
        setModifyTime(value);
        return this;
    }

    @Override
    public SystemOptionRecord value7(Long value) {
        setTenantId(value);
        return this;
    }

    @Override
    public SystemOptionRecord values(Integer value1, String value2, String value3, String value4, LocalDateTime value5, LocalDateTime value6, Long value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SystemOptionRecord
     */
    public SystemOptionRecord() {
        super(SystemOption.SYSTEM_OPTION);
    }

    /**
     * Create a detached, initialised SystemOptionRecord
     */
    public SystemOptionRecord(Integer id, String type, String keyString, String valueText, LocalDateTime createTime, LocalDateTime modifyTime, Long tenantId) {
        super(SystemOption.SYSTEM_OPTION);

        set(0, id);
        set(1, type);
        set(2, keyString);
        set(3, valueText);
        set(4, createTime);
        set(5, modifyTime);
        set(6, tenantId);
    }
}
