/*
 * This file is generated by jOOQ.
 */
package com.svnlan.jooq.tables.records;


import com.svnlan.jooq.tables.TTenant;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 租户表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TTenantRecord extends UpdatableRecordImpl<TTenantRecord> implements Record15<Long, String, String, Long, Integer, LocalDateTime, LocalDateTime, Long, Long, Long, String, LocalDateTime, LocalDateTime, Integer, Integer> {

    private static final long serialVersionUID = 677454870;

    /**
     * Setter for <code>cloud_disk.t_tenant.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>cloud_disk.t_tenant.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>cloud_disk.t_tenant.tenant_name</code>. 名称
     */
    public void setTenantName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cloud_disk.t_tenant.tenant_name</code>. 名称
     */
    public String getTenantName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cloud_disk.t_tenant.second_level_domain</code>. 二级域名
     */
    public void setSecondLevelDomain(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>cloud_disk.t_tenant.second_level_domain</code>. 二级域名
     */
    public String getSecondLevelDomain() {
        return (String) get(2);
    }

    /**
     * Setter for <code>cloud_disk.t_tenant.user_id</code>. 超级管理员，用户id
     */
    public void setUserId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>cloud_disk.t_tenant.user_id</code>. 超级管理员，用户id
     */
    public Long getUserId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>cloud_disk.t_tenant.status</code>. 状态，0停用，1启用，2删除
     */
    public void setStatus(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>cloud_disk.t_tenant.status</code>. 状态，0停用，1启用，2删除
     */
    public Integer getStatus() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>cloud_disk.t_tenant.start_time</code>. 生效时间
     */
    public void setStartTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>cloud_disk.t_tenant.start_time</code>. 生效时间
     */
    public LocalDateTime getStartTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>cloud_disk.t_tenant.expire_time</code>. 失效时间
     */
    public void setExpireTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>cloud_disk.t_tenant.expire_time</code>. 失效时间
     */
    public LocalDateTime getExpireTime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>cloud_disk.t_tenant.size_use</code>. 已使用大小(byte)
     */
    public void setSizeUse(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>cloud_disk.t_tenant.size_use</code>. 已使用大小(byte)
     */
    public Long getSizeUse() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>cloud_disk.t_tenant.group_count</code>. 组织数
     */
    public void setGroupCount(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>cloud_disk.t_tenant.group_count</code>. 组织数
     */
    public Long getGroupCount() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>cloud_disk.t_tenant.user_count</code>. 用户数
     */
    public void setUserCount(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>cloud_disk.t_tenant.user_count</code>. 用户数
     */
    public Long getUserCount() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>cloud_disk.t_tenant.remark</code>. 备注
     */
    public void setRemark(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>cloud_disk.t_tenant.remark</code>. 备注
     */
    public String getRemark() {
        return (String) get(10);
    }

    /**
     * Setter for <code>cloud_disk.t_tenant.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>cloud_disk.t_tenant.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>cloud_disk.t_tenant.modify_time</code>. 最后修改
     */
    public void setModifyTime(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>cloud_disk.t_tenant.modify_time</code>. 最后修改
     */
    public LocalDateTime getModifyTime() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>cloud_disk.t_tenant.dr</code>. 逻辑删除 0 未删除 1 已删除
     */
    public void setDr(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>cloud_disk.t_tenant.dr</code>. 逻辑删除 0 未删除 1 已删除
     */
    public Integer getDr() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>cloud_disk.t_tenant.is_system</code>. 是否是系统租户  0 否 1 是
     */
    public void setIsSystem(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>cloud_disk.t_tenant.is_system</code>. 是否是系统租户  0 否 1 是
     */
    public Integer getIsSystem() {
        return (Integer) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row15<Long, String, String, Long, Integer, LocalDateTime, LocalDateTime, Long, Long, Long, String, LocalDateTime, LocalDateTime, Integer, Integer> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    @Override
    public Row15<Long, String, String, Long, Integer, LocalDateTime, LocalDateTime, Long, Long, Long, String, LocalDateTime, LocalDateTime, Integer, Integer> valuesRow() {
        return (Row15) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TTenant.T_TENANT.ID;
    }

    @Override
    public Field<String> field2() {
        return TTenant.T_TENANT.TENANT_NAME;
    }

    @Override
    public Field<String> field3() {
        return TTenant.T_TENANT.SECOND_LEVEL_DOMAIN;
    }

    @Override
    public Field<Long> field4() {
        return TTenant.T_TENANT.USER_ID;
    }

    @Override
    public Field<Integer> field5() {
        return TTenant.T_TENANT.STATUS;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return TTenant.T_TENANT.START_TIME;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return TTenant.T_TENANT.EXPIRE_TIME;
    }

    @Override
    public Field<Long> field8() {
        return TTenant.T_TENANT.SIZE_USE;
    }

    @Override
    public Field<Long> field9() {
        return TTenant.T_TENANT.GROUP_COUNT;
    }

    @Override
    public Field<Long> field10() {
        return TTenant.T_TENANT.USER_COUNT;
    }

    @Override
    public Field<String> field11() {
        return TTenant.T_TENANT.REMARK;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return TTenant.T_TENANT.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field13() {
        return TTenant.T_TENANT.MODIFY_TIME;
    }

    @Override
    public Field<Integer> field14() {
        return TTenant.T_TENANT.DR;
    }

    @Override
    public Field<Integer> field15() {
        return TTenant.T_TENANT.IS_SYSTEM;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTenantName();
    }

    @Override
    public String component3() {
        return getSecondLevelDomain();
    }

    @Override
    public Long component4() {
        return getUserId();
    }

    @Override
    public Integer component5() {
        return getStatus();
    }

    @Override
    public LocalDateTime component6() {
        return getStartTime();
    }

    @Override
    public LocalDateTime component7() {
        return getExpireTime();
    }

    @Override
    public Long component8() {
        return getSizeUse();
    }

    @Override
    public Long component9() {
        return getGroupCount();
    }

    @Override
    public Long component10() {
        return getUserCount();
    }

    @Override
    public String component11() {
        return getRemark();
    }

    @Override
    public LocalDateTime component12() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component13() {
        return getModifyTime();
    }

    @Override
    public Integer component14() {
        return getDr();
    }

    @Override
    public Integer component15() {
        return getIsSystem();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTenantName();
    }

    @Override
    public String value3() {
        return getSecondLevelDomain();
    }

    @Override
    public Long value4() {
        return getUserId();
    }

    @Override
    public Integer value5() {
        return getStatus();
    }

    @Override
    public LocalDateTime value6() {
        return getStartTime();
    }

    @Override
    public LocalDateTime value7() {
        return getExpireTime();
    }

    @Override
    public Long value8() {
        return getSizeUse();
    }

    @Override
    public Long value9() {
        return getGroupCount();
    }

    @Override
    public Long value10() {
        return getUserCount();
    }

    @Override
    public String value11() {
        return getRemark();
    }

    @Override
    public LocalDateTime value12() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value13() {
        return getModifyTime();
    }

    @Override
    public Integer value14() {
        return getDr();
    }

    @Override
    public Integer value15() {
        return getIsSystem();
    }

    @Override
    public TTenantRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TTenantRecord value2(String value) {
        setTenantName(value);
        return this;
    }

    @Override
    public TTenantRecord value3(String value) {
        setSecondLevelDomain(value);
        return this;
    }

    @Override
    public TTenantRecord value4(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public TTenantRecord value5(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public TTenantRecord value6(LocalDateTime value) {
        setStartTime(value);
        return this;
    }

    @Override
    public TTenantRecord value7(LocalDateTime value) {
        setExpireTime(value);
        return this;
    }

    @Override
    public TTenantRecord value8(Long value) {
        setSizeUse(value);
        return this;
    }

    @Override
    public TTenantRecord value9(Long value) {
        setGroupCount(value);
        return this;
    }

    @Override
    public TTenantRecord value10(Long value) {
        setUserCount(value);
        return this;
    }

    @Override
    public TTenantRecord value11(String value) {
        setRemark(value);
        return this;
    }

    @Override
    public TTenantRecord value12(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public TTenantRecord value13(LocalDateTime value) {
        setModifyTime(value);
        return this;
    }

    @Override
    public TTenantRecord value14(Integer value) {
        setDr(value);
        return this;
    }

    @Override
    public TTenantRecord value15(Integer value) {
        setIsSystem(value);
        return this;
    }

    @Override
    public TTenantRecord values(Long value1, String value2, String value3, Long value4, Integer value5, LocalDateTime value6, LocalDateTime value7, Long value8, Long value9, Long value10, String value11, LocalDateTime value12, LocalDateTime value13, Integer value14, Integer value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TTenantRecord
     */
    public TTenantRecord() {
        super(TTenant.T_TENANT);
    }

    /**
     * Create a detached, initialised TTenantRecord
     */
    public TTenantRecord(Long id, String tenantName, String secondLevelDomain, Long userId, Integer status, LocalDateTime startTime, LocalDateTime expireTime, Long sizeUse, Long groupCount, Long userCount, String remark, LocalDateTime createTime, LocalDateTime modifyTime, Integer dr, Integer isSystem) {
        super(TTenant.T_TENANT);

        set(0, id);
        set(1, tenantName);
        set(2, secondLevelDomain);
        set(3, userId);
        set(4, status);
        set(5, startTime);
        set(6, expireTime);
        set(7, sizeUse);
        set(8, groupCount);
        set(9, userCount);
        set(10, remark);
        set(11, createTime);
        set(12, modifyTime);
        set(13, dr);
        set(14, isSystem);
    }
}
