/*
 * This file is generated by jOOQ.
 */
package com.svnlan.jooq.tables.records;


import com.svnlan.jooq.tables.UserFav;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 用户文档标签表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserFavRecord extends UpdatableRecordImpl<UserFavRecord> implements Record10<Long, Long, Integer, String, String, String, Integer, LocalDateTime, LocalDateTime, Long> {

    private static final long serialVersionUID = 1421796181;

    /**
     * Setter for <code>cloud_disk.user_fav.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>cloud_disk.user_fav.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>cloud_disk.user_fav.user_id</code>. 用户id
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>cloud_disk.user_fav.user_id</code>. 用户id
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>cloud_disk.user_fav.tag_id</code>. 标签id,收藏则为0
     */
    public void setTagId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>cloud_disk.user_fav.tag_id</code>. 标签id,收藏则为0
     */
    public Integer getTagId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>cloud_disk.user_fav.name</code>. 收藏名称
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>cloud_disk.user_fav.name</code>. 收藏名称
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>cloud_disk.user_fav.path</code>. 收藏路径,tag时则为sourceID
     */
    public void setPath(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>cloud_disk.user_fav.path</code>. 收藏路径,tag时则为sourceID
     */
    public String getPath() {
        return (String) get(4);
    }

    /**
     * Setter for <code>cloud_disk.user_fav.type</code>. source/path/info
     */
    public void setType(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>cloud_disk.user_fav.type</code>. source/path/info
     */
    public String getType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>cloud_disk.user_fav.sort</code>. 排序
     */
    public void setSort(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>cloud_disk.user_fav.sort</code>. 排序
     */
    public Integer getSort() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>cloud_disk.user_fav.modify_time</code>. 最后修改时间
     */
    public void setModifyTime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>cloud_disk.user_fav.modify_time</code>. 最后修改时间
     */
    public LocalDateTime getModifyTime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>cloud_disk.user_fav.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>cloud_disk.user_fav.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>cloud_disk.user_fav.tenant_id</code>. 租户id
     */
    public void setTenantId(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>cloud_disk.user_fav.tenant_id</code>. 租户id
     */
    public Long getTenantId() {
        return (Long) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, Long, Integer, String, String, String, Integer, LocalDateTime, LocalDateTime, Long> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, Long, Integer, String, String, String, Integer, LocalDateTime, LocalDateTime, Long> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UserFav.USER_FAV.ID;
    }

    @Override
    public Field<Long> field2() {
        return UserFav.USER_FAV.USER_ID;
    }

    @Override
    public Field<Integer> field3() {
        return UserFav.USER_FAV.TAG_ID;
    }

    @Override
    public Field<String> field4() {
        return UserFav.USER_FAV.NAME;
    }

    @Override
    public Field<String> field5() {
        return UserFav.USER_FAV.PATH;
    }

    @Override
    public Field<String> field6() {
        return UserFav.USER_FAV.TYPE;
    }

    @Override
    public Field<Integer> field7() {
        return UserFav.USER_FAV.SORT;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return UserFav.USER_FAV.MODIFY_TIME;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return UserFav.USER_FAV.CREATE_TIME;
    }

    @Override
    public Field<Long> field10() {
        return UserFav.USER_FAV.TENANT_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getUserId();
    }

    @Override
    public Integer component3() {
        return getTagId();
    }

    @Override
    public String component4() {
        return getName();
    }

    @Override
    public String component5() {
        return getPath();
    }

    @Override
    public String component6() {
        return getType();
    }

    @Override
    public Integer component7() {
        return getSort();
    }

    @Override
    public LocalDateTime component8() {
        return getModifyTime();
    }

    @Override
    public LocalDateTime component9() {
        return getCreateTime();
    }

    @Override
    public Long component10() {
        return getTenantId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getUserId();
    }

    @Override
    public Integer value3() {
        return getTagId();
    }

    @Override
    public String value4() {
        return getName();
    }

    @Override
    public String value5() {
        return getPath();
    }

    @Override
    public String value6() {
        return getType();
    }

    @Override
    public Integer value7() {
        return getSort();
    }

    @Override
    public LocalDateTime value8() {
        return getModifyTime();
    }

    @Override
    public LocalDateTime value9() {
        return getCreateTime();
    }

    @Override
    public Long value10() {
        return getTenantId();
    }

    @Override
    public UserFavRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public UserFavRecord value2(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public UserFavRecord value3(Integer value) {
        setTagId(value);
        return this;
    }

    @Override
    public UserFavRecord value4(String value) {
        setName(value);
        return this;
    }

    @Override
    public UserFavRecord value5(String value) {
        setPath(value);
        return this;
    }

    @Override
    public UserFavRecord value6(String value) {
        setType(value);
        return this;
    }

    @Override
    public UserFavRecord value7(Integer value) {
        setSort(value);
        return this;
    }

    @Override
    public UserFavRecord value8(LocalDateTime value) {
        setModifyTime(value);
        return this;
    }

    @Override
    public UserFavRecord value9(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public UserFavRecord value10(Long value) {
        setTenantId(value);
        return this;
    }

    @Override
    public UserFavRecord values(Long value1, Long value2, Integer value3, String value4, String value5, String value6, Integer value7, LocalDateTime value8, LocalDateTime value9, Long value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserFavRecord
     */
    public UserFavRecord() {
        super(UserFav.USER_FAV);
    }

    /**
     * Create a detached, initialised UserFavRecord
     */
    public UserFavRecord(Long id, Long userId, Integer tagId, String name, String path, String type, Integer sort, LocalDateTime modifyTime, LocalDateTime createTime, Long tenantId) {
        super(UserFav.USER_FAV);

        set(0, id);
        set(1, userId);
        set(2, tagId);
        set(3, name);
        set(4, path);
        set(5, type);
        set(6, sort);
        set(7, modifyTime);
        set(8, createTime);
        set(9, tenantId);
    }
}
