#source `源地址`
source 'https://github.com/CocoaPods/Specs.git'

project 'FilesBox.xcodeproj'

platform :ios, '9.0'
inhibit_all_warnings!

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['ARCHS'] = 'arm64'
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end

target 'FilesBox' do
  use_frameworks!
  
  pod 'AFNetworking', '3.1.0'

# remove UIKit(UIWebView) rejected by AppStore
pre_install do |installer|
    puts 'pre_install begin....'
    dir_af = File.join(installer.sandbox.pod_dir('AFNetworking'), 'UIKit+AFNetworking')
    Dir.foreach(dir_af) {|x|
      real_path = File.join(dir_af, x)
      if (!File.directory?(real_path) && File.exists?(real_path))
        if((x.start_with?('UIWebView') || x == 'UIKit+AFNetworking.h'))
          File.delete(real_path)
          puts 'delete:'+ x
        end
      end
    }
    puts 'end pre_install.'
end
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'Masonry'
  pod 'ASIHTTPRequest'
  pod 'MBProgressHUD'
  pod 'ReactiveObjC'
  pod 'YYKit'
  pod 'IQKeyboardManager', '~> 6.5.0’
  pod 'Reachability'
  pod 'TYPagerController'
  pod 'SocketRocket'
  pod 'CYLTabBarController', '~> 1.28.3'
  pod 'TZImagePickerController'
  pod 'JXCategoryView' ,'~> 1.5.8'
  pod 'JXPagingView/Pager'
  pod 'Realm','~> 3.13'
  pod "TTGTagCollectionView" ,'~> 1.11.1'
  pod 'zhPopupController'
  pod 'SVGKit'
  pod 'SWTableViewCell'
  pod 'WZLBadge'
  pod 'ZipArchive', '~> 1.4'
  pod 'GTSDK'
  pod 'IJKMediaFramework', :git => 'https://gitee.com/renzifeng/IJKMediaFramework.git'
  pod 'LBXScan/LBXNative'
  pod 'LBXScan/UI'
  pod 'FMDB'
  pod 'SJXSignTextView'
  pod "MSColorPicker"
  pod 'TKCarouselView'
  pod 'YBAttributeTextTapAction'
  pod 'WechatOpenSDK'
  pod 'PSImageEditors'
  pod "Weibo_SDK", :git => "https://github.com/sinaweibosdk/weibo_ios_sdk.git" 
  pod 'SDWebImage'

end



