/*
 * This file is generated by jOOQ.
 */
package com.svnlan.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * 通用评论表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommentModel implements Serializable {

    private static final long serialVersionUID = 703860011;

    protected Long          id;
    protected Long          pid;
    protected Long          userId;
    protected Integer       targetType;
    protected Long          targetId;
    protected String        content;
    protected Integer       praiseCount;
    protected Integer       commentCount;
    protected Integer       status;
    protected LocalDateTime modifyTime;
    protected LocalDateTime createTime;
    protected Long          tenantId;

    public CommentModel() {}

    public CommentModel(CommentModel value) {
        this.id = value.id;
        this.pid = value.pid;
        this.userId = value.userId;
        this.targetType = value.targetType;
        this.targetId = value.targetId;
        this.content = value.content;
        this.praiseCount = value.praiseCount;
        this.commentCount = value.commentCount;
        this.status = value.status;
        this.modifyTime = value.modifyTime;
        this.createTime = value.createTime;
        this.tenantId = value.tenantId;
    }

    public CommentModel(
        Long          id,
        Long          pid,
        Long          userId,
        Integer       targetType,
        Long          targetId,
        String        content,
        Integer       praiseCount,
        Integer       commentCount,
        Integer       status,
        LocalDateTime modifyTime,
        LocalDateTime createTime,
        Long          tenantId
    ) {
        this.id = id;
        this.pid = pid;
        this.userId = userId;
        this.targetType = targetType;
        this.targetId = targetId;
        this.content = content;
        this.praiseCount = praiseCount;
        this.commentCount = commentCount;
        this.status = status;
        this.modifyTime = modifyTime;
        this.createTime = createTime;
        this.tenantId = tenantId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getPid() {
        return this.pid;
    }

    public void setPid(Long pid) {
        this.pid = pid;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Integer getTargetType() {
        return this.targetType;
    }

    public void setTargetType(Integer targetType) {
        this.targetType = targetType;
    }

    public Long getTargetId() {
        return this.targetId;
    }

    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Integer getPraiseCount() {
        return this.praiseCount;
    }

    public void setPraiseCount(Integer praiseCount) {
        this.praiseCount = praiseCount;
    }

    public Integer getCommentCount() {
        return this.commentCount;
    }

    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public LocalDateTime getModifyTime() {
        return this.modifyTime;
    }

    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public Long getTenantId() {
        return this.tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CommentModel (");

        sb.append(id);
        sb.append(", ").append(pid);
        sb.append(", ").append(userId);
        sb.append(", ").append(targetType);
        sb.append(", ").append(targetId);
        sb.append(", ").append(content);
        sb.append(", ").append(praiseCount);
        sb.append(", ").append(commentCount);
        sb.append(", ").append(status);
        sb.append(", ").append(modifyTime);
        sb.append(", ").append(createTime);
        sb.append(", ").append(tenantId);

        sb.append(")");
        return sb.toString();
    }
}
