/*
 * This file is generated by jOOQ.
 */
package com.svnlan.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * 资讯类型表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommonInfoTypeModel implements Serializable {

    private static final long serialVersionUID = 2002702765;

    protected Integer       id;
    protected String        typeName;
    protected Integer       parentId;
    protected String        parentLevel;
    protected Integer       status;
    protected Integer       sort;
    protected String        namePinyin;
    protected String        namePinyinSimple;
    protected Long          createUser;
    protected LocalDateTime createTime;
    protected LocalDateTime modifyTime;
    protected Long          tenantId;

    public CommonInfoTypeModel() {}

    public CommonInfoTypeModel(CommonInfoTypeModel value) {
        this.id = value.id;
        this.typeName = value.typeName;
        this.parentId = value.parentId;
        this.parentLevel = value.parentLevel;
        this.status = value.status;
        this.sort = value.sort;
        this.namePinyin = value.namePinyin;
        this.namePinyinSimple = value.namePinyinSimple;
        this.createUser = value.createUser;
        this.createTime = value.createTime;
        this.modifyTime = value.modifyTime;
        this.tenantId = value.tenantId;
    }

    public CommonInfoTypeModel(
        Integer       id,
        String        typeName,
        Integer       parentId,
        String        parentLevel,
        Integer       status,
        Integer       sort,
        String        namePinyin,
        String        namePinyinSimple,
        Long          createUser,
        LocalDateTime createTime,
        LocalDateTime modifyTime,
        Long          tenantId
    ) {
        this.id = id;
        this.typeName = typeName;
        this.parentId = parentId;
        this.parentLevel = parentLevel;
        this.status = status;
        this.sort = sort;
        this.namePinyin = namePinyin;
        this.namePinyinSimple = namePinyinSimple;
        this.createUser = createUser;
        this.createTime = createTime;
        this.modifyTime = modifyTime;
        this.tenantId = tenantId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTypeName() {
        return this.typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    public Integer getParentId() {
        return this.parentId;
    }

    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    public String getParentLevel() {
        return this.parentLevel;
    }

    public void setParentLevel(String parentLevel) {
        this.parentLevel = parentLevel;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getSort() {
        return this.sort;
    }

    public void setSort(Integer sort) {
        this.sort = sort;
    }

    public String getNamePinyin() {
        return this.namePinyin;
    }

    public void setNamePinyin(String namePinyin) {
        this.namePinyin = namePinyin;
    }

    public String getNamePinyinSimple() {
        return this.namePinyinSimple;
    }

    public void setNamePinyinSimple(String namePinyinSimple) {
        this.namePinyinSimple = namePinyinSimple;
    }

    public Long getCreateUser() {
        return this.createUser;
    }

    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public LocalDateTime getModifyTime() {
        return this.modifyTime;
    }

    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    public Long getTenantId() {
        return this.tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CommonInfoTypeModel (");

        sb.append(id);
        sb.append(", ").append(typeName);
        sb.append(", ").append(parentId);
        sb.append(", ").append(parentLevel);
        sb.append(", ").append(status);
        sb.append(", ").append(sort);
        sb.append(", ").append(namePinyin);
        sb.append(", ").append(namePinyinSimple);
        sb.append(", ").append(createUser);
        sb.append(", ").append(createTime);
        sb.append(", ").append(modifyTime);
        sb.append(", ").append(tenantId);

        sb.append(")");
        return sb.toString();
    }
}
