/*
 * This file is generated by jOOQ.
 */
package com.svnlan.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * 标签表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommonLabelModel implements Serializable {

    private static final long serialVersionUID = -2035971896;

    protected Long          id;
    protected Long          userId;
    protected String        labelName;
    protected String        labelEnName;
    protected String        enNameSimple;
    protected Integer       status;
    protected String        style;
    protected Integer       sort;
    protected Integer       tagType;
    protected LocalDateTime createTime;
    protected LocalDateTime modifyTime;
    protected Long          tenantId;

    public CommonLabelModel() {}

    public CommonLabelModel(CommonLabelModel value) {
        this.id = value.id;
        this.userId = value.userId;
        this.labelName = value.labelName;
        this.labelEnName = value.labelEnName;
        this.enNameSimple = value.enNameSimple;
        this.status = value.status;
        this.style = value.style;
        this.sort = value.sort;
        this.tagType = value.tagType;
        this.createTime = value.createTime;
        this.modifyTime = value.modifyTime;
        this.tenantId = value.tenantId;
    }

    public CommonLabelModel(
        Long          id,
        Long          userId,
        String        labelName,
        String        labelEnName,
        String        enNameSimple,
        Integer       status,
        String        style,
        Integer       sort,
        Integer       tagType,
        LocalDateTime createTime,
        LocalDateTime modifyTime,
        Long          tenantId
    ) {
        this.id = id;
        this.userId = userId;
        this.labelName = labelName;
        this.labelEnName = labelEnName;
        this.enNameSimple = enNameSimple;
        this.status = status;
        this.style = style;
        this.sort = sort;
        this.tagType = tagType;
        this.createTime = createTime;
        this.modifyTime = modifyTime;
        this.tenantId = tenantId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getLabelName() {
        return this.labelName;
    }

    public void setLabelName(String labelName) {
        this.labelName = labelName;
    }

    public String getLabelEnName() {
        return this.labelEnName;
    }

    public void setLabelEnName(String labelEnName) {
        this.labelEnName = labelEnName;
    }

    public String getEnNameSimple() {
        return this.enNameSimple;
    }

    public void setEnNameSimple(String enNameSimple) {
        this.enNameSimple = enNameSimple;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getStyle() {
        return this.style;
    }

    public void setStyle(String style) {
        this.style = style;
    }

    public Integer getSort() {
        return this.sort;
    }

    public void setSort(Integer sort) {
        this.sort = sort;
    }

    public Integer getTagType() {
        return this.tagType;
    }

    public void setTagType(Integer tagType) {
        this.tagType = tagType;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public LocalDateTime getModifyTime() {
        return this.modifyTime;
    }

    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    public Long getTenantId() {
        return this.tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CommonLabelModel (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(labelName);
        sb.append(", ").append(labelEnName);
        sb.append(", ").append(enNameSimple);
        sb.append(", ").append(status);
        sb.append(", ").append(style);
        sb.append(", ").append(sort);
        sb.append(", ").append(tagType);
        sb.append(", ").append(createTime);
        sb.append(", ").append(modifyTime);
        sb.append(", ").append(tenantId);

        sb.append(")");
        return sb.toString();
    }
}
