/*
 * This file is generated by jOOQ.
 */
package com.svnlan.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * 页面编辑器表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommonDesignModel implements Serializable {

    private static final long serialVersionUID = 807091337;

    protected Long          id;
    protected String        title;
    protected String        offset;
    protected String        size;
    protected Long          pic;
    protected LocalDateTime gmtCreate;
    protected LocalDateTime gmtModified;
    protected String        detail;
    protected String        designType;
    protected String        clientType;
    protected Integer       isUsed;
    protected String        url;
    protected String        fileUrl;
    protected Long          fkCommonDesignId;
    protected String        foot;
    protected String        head;
    protected String        setting;
    protected String        applet;
    protected Long          sourceDesignId;
    protected String        approvalState;
    protected String        approvalDetail;
    protected LocalDateTime gmtApproval;
    protected Integer       sort;
    protected String        state;
    protected Integer       isPaste;
    protected String        seo;
    protected Long          mbDesignId;
    protected Integer       designClassifyId;
    protected String        pathPre;
    protected Long          tenantId;

    public CommonDesignModel() {}

    public CommonDesignModel(CommonDesignModel value) {
        this.id = value.id;
        this.title = value.title;
        this.offset = value.offset;
        this.size = value.size;
        this.pic = value.pic;
        this.gmtCreate = value.gmtCreate;
        this.gmtModified = value.gmtModified;
        this.detail = value.detail;
        this.designType = value.designType;
        this.clientType = value.clientType;
        this.isUsed = value.isUsed;
        this.url = value.url;
        this.fileUrl = value.fileUrl;
        this.fkCommonDesignId = value.fkCommonDesignId;
        this.foot = value.foot;
        this.head = value.head;
        this.setting = value.setting;
        this.applet = value.applet;
        this.sourceDesignId = value.sourceDesignId;
        this.approvalState = value.approvalState;
        this.approvalDetail = value.approvalDetail;
        this.gmtApproval = value.gmtApproval;
        this.sort = value.sort;
        this.state = value.state;
        this.isPaste = value.isPaste;
        this.seo = value.seo;
        this.mbDesignId = value.mbDesignId;
        this.designClassifyId = value.designClassifyId;
        this.pathPre = value.pathPre;
        this.tenantId = value.tenantId;
    }

    public CommonDesignModel(
        Long          id,
        String        title,
        String        offset,
        String        size,
        Long          pic,
        LocalDateTime gmtCreate,
        LocalDateTime gmtModified,
        String        detail,
        String        designType,
        String        clientType,
        Integer       isUsed,
        String        url,
        String        fileUrl,
        Long          fkCommonDesignId,
        String        foot,
        String        head,
        String        setting,
        String        applet,
        Long          sourceDesignId,
        String        approvalState,
        String        approvalDetail,
        LocalDateTime gmtApproval,
        Integer       sort,
        String        state,
        Integer       isPaste,
        String        seo,
        Long          mbDesignId,
        Integer       designClassifyId,
        String        pathPre,
        Long          tenantId
    ) {
        this.id = id;
        this.title = title;
        this.offset = offset;
        this.size = size;
        this.pic = pic;
        this.gmtCreate = gmtCreate;
        this.gmtModified = gmtModified;
        this.detail = detail;
        this.designType = designType;
        this.clientType = clientType;
        this.isUsed = isUsed;
        this.url = url;
        this.fileUrl = fileUrl;
        this.fkCommonDesignId = fkCommonDesignId;
        this.foot = foot;
        this.head = head;
        this.setting = setting;
        this.applet = applet;
        this.sourceDesignId = sourceDesignId;
        this.approvalState = approvalState;
        this.approvalDetail = approvalDetail;
        this.gmtApproval = gmtApproval;
        this.sort = sort;
        this.state = state;
        this.isPaste = isPaste;
        this.seo = seo;
        this.mbDesignId = mbDesignId;
        this.designClassifyId = designClassifyId;
        this.pathPre = pathPre;
        this.tenantId = tenantId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getOffset() {
        return this.offset;
    }

    public void setOffset(String offset) {
        this.offset = offset;
    }

    public String getSize() {
        return this.size;
    }

    public void setSize(String size) {
        this.size = size;
    }

    public Long getPic() {
        return this.pic;
    }

    public void setPic(Long pic) {
        this.pic = pic;
    }

    public LocalDateTime getGmtCreate() {
        return this.gmtCreate;
    }

    public void setGmtCreate(LocalDateTime gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    public LocalDateTime getGmtModified() {
        return this.gmtModified;
    }

    public void setGmtModified(LocalDateTime gmtModified) {
        this.gmtModified = gmtModified;
    }

    public String getDetail() {
        return this.detail;
    }

    public void setDetail(String detail) {
        this.detail = detail;
    }

    public String getDesignType() {
        return this.designType;
    }

    public void setDesignType(String designType) {
        this.designType = designType;
    }

    public String getClientType() {
        return this.clientType;
    }

    public void setClientType(String clientType) {
        this.clientType = clientType;
    }

    public Integer getIsUsed() {
        return this.isUsed;
    }

    public void setIsUsed(Integer isUsed) {
        this.isUsed = isUsed;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getFileUrl() {
        return this.fileUrl;
    }

    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl;
    }

    public Long getFkCommonDesignId() {
        return this.fkCommonDesignId;
    }

    public void setFkCommonDesignId(Long fkCommonDesignId) {
        this.fkCommonDesignId = fkCommonDesignId;
    }

    public String getFoot() {
        return this.foot;
    }

    public void setFoot(String foot) {
        this.foot = foot;
    }

    public String getHead() {
        return this.head;
    }

    public void setHead(String head) {
        this.head = head;
    }

    public String getSetting() {
        return this.setting;
    }

    public void setSetting(String setting) {
        this.setting = setting;
    }

    public String getApplet() {
        return this.applet;
    }

    public void setApplet(String applet) {
        this.applet = applet;
    }

    public Long getSourceDesignId() {
        return this.sourceDesignId;
    }

    public void setSourceDesignId(Long sourceDesignId) {
        this.sourceDesignId = sourceDesignId;
    }

    public String getApprovalState() {
        return this.approvalState;
    }

    public void setApprovalState(String approvalState) {
        this.approvalState = approvalState;
    }

    public String getApprovalDetail() {
        return this.approvalDetail;
    }

    public void setApprovalDetail(String approvalDetail) {
        this.approvalDetail = approvalDetail;
    }

    public LocalDateTime getGmtApproval() {
        return this.gmtApproval;
    }

    public void setGmtApproval(LocalDateTime gmtApproval) {
        this.gmtApproval = gmtApproval;
    }

    public Integer getSort() {
        return this.sort;
    }

    public void setSort(Integer sort) {
        this.sort = sort;
    }

    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public Integer getIsPaste() {
        return this.isPaste;
    }

    public void setIsPaste(Integer isPaste) {
        this.isPaste = isPaste;
    }

    public String getSeo() {
        return this.seo;
    }

    public void setSeo(String seo) {
        this.seo = seo;
    }

    public Long getMbDesignId() {
        return this.mbDesignId;
    }

    public void setMbDesignId(Long mbDesignId) {
        this.mbDesignId = mbDesignId;
    }

    public Integer getDesignClassifyId() {
        return this.designClassifyId;
    }

    public void setDesignClassifyId(Integer designClassifyId) {
        this.designClassifyId = designClassifyId;
    }

    public String getPathPre() {
        return this.pathPre;
    }

    public void setPathPre(String pathPre) {
        this.pathPre = pathPre;
    }

    public Long getTenantId() {
        return this.tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CommonDesignModel (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(offset);
        sb.append(", ").append(size);
        sb.append(", ").append(pic);
        sb.append(", ").append(gmtCreate);
        sb.append(", ").append(gmtModified);
        sb.append(", ").append(detail);
        sb.append(", ").append(designType);
        sb.append(", ").append(clientType);
        sb.append(", ").append(isUsed);
        sb.append(", ").append(url);
        sb.append(", ").append(fileUrl);
        sb.append(", ").append(fkCommonDesignId);
        sb.append(", ").append(foot);
        sb.append(", ").append(head);
        sb.append(", ").append(setting);
        sb.append(", ").append(applet);
        sb.append(", ").append(sourceDesignId);
        sb.append(", ").append(approvalState);
        sb.append(", ").append(approvalDetail);
        sb.append(", ").append(gmtApproval);
        sb.append(", ").append(sort);
        sb.append(", ").append(state);
        sb.append(", ").append(isPaste);
        sb.append(", ").append(seo);
        sb.append(", ").append(mbDesignId);
        sb.append(", ").append(designClassifyId);
        sb.append(", ").append(pathPre);
        sb.append(", ").append(tenantId);

        sb.append(")");
        return sb.toString();
    }
}
