/*
 * This file is generated by jOOQ.
 */
package com.svnlan.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * 转码表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommonConvertModel implements Serializable {

    private static final long serialVersionUID = -1365094139;

    protected Long          id;
    protected Long          sourceId;
    protected Long          fileId;
    protected Long          userId;
    protected String        name;
    protected Integer       frequencyCount;
    protected String        state;
    protected String        remark;
    protected Integer       scheduleFrequencyCount;
    protected LocalDateTime modifyTime;
    protected LocalDateTime createTime;
    protected LocalDateTime scheduleTime;
    protected Long          tenantId;

    public CommonConvertModel() {}

    public CommonConvertModel(CommonConvertModel value) {
        this.id = value.id;
        this.sourceId = value.sourceId;
        this.fileId = value.fileId;
        this.userId = value.userId;
        this.name = value.name;
        this.frequencyCount = value.frequencyCount;
        this.state = value.state;
        this.remark = value.remark;
        this.scheduleFrequencyCount = value.scheduleFrequencyCount;
        this.modifyTime = value.modifyTime;
        this.createTime = value.createTime;
        this.scheduleTime = value.scheduleTime;
        this.tenantId = value.tenantId;
    }

    public CommonConvertModel(
        Long          id,
        Long          sourceId,
        Long          fileId,
        Long          userId,
        String        name,
        Integer       frequencyCount,
        String        state,
        String        remark,
        Integer       scheduleFrequencyCount,
        LocalDateTime modifyTime,
        LocalDateTime createTime,
        LocalDateTime scheduleTime,
        Long          tenantId
    ) {
        this.id = id;
        this.sourceId = sourceId;
        this.fileId = fileId;
        this.userId = userId;
        this.name = name;
        this.frequencyCount = frequencyCount;
        this.state = state;
        this.remark = remark;
        this.scheduleFrequencyCount = scheduleFrequencyCount;
        this.modifyTime = modifyTime;
        this.createTime = createTime;
        this.scheduleTime = scheduleTime;
        this.tenantId = tenantId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getSourceId() {
        return this.sourceId;
    }

    public void setSourceId(Long sourceId) {
        this.sourceId = sourceId;
    }

    public Long getFileId() {
        return this.fileId;
    }

    public void setFileId(Long fileId) {
        this.fileId = fileId;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getFrequencyCount() {
        return this.frequencyCount;
    }

    public void setFrequencyCount(Integer frequencyCount) {
        this.frequencyCount = frequencyCount;
    }

    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Integer getScheduleFrequencyCount() {
        return this.scheduleFrequencyCount;
    }

    public void setScheduleFrequencyCount(Integer scheduleFrequencyCount) {
        this.scheduleFrequencyCount = scheduleFrequencyCount;
    }

    public LocalDateTime getModifyTime() {
        return this.modifyTime;
    }

    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public LocalDateTime getScheduleTime() {
        return this.scheduleTime;
    }

    public void setScheduleTime(LocalDateTime scheduleTime) {
        this.scheduleTime = scheduleTime;
    }

    public Long getTenantId() {
        return this.tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CommonConvertModel (");

        sb.append(id);
        sb.append(", ").append(sourceId);
        sb.append(", ").append(fileId);
        sb.append(", ").append(userId);
        sb.append(", ").append(name);
        sb.append(", ").append(frequencyCount);
        sb.append(", ").append(state);
        sb.append(", ").append(remark);
        sb.append(", ").append(scheduleFrequencyCount);
        sb.append(", ").append(modifyTime);
        sb.append(", ").append(createTime);
        sb.append(", ").append(scheduleTime);
        sb.append(", ").append(tenantId);

        sb.append(")");
        return sb.toString();
    }
}
