/*
 * This file is generated by jOOQ.
 */
package com.svnlan.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * 群组表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupsModel implements Serializable {

    private static final long serialVersionUID = 1197707330;

    protected Long          id;
    protected String        name;
    protected Long          parentId;
    protected String        parentLevel;
    protected String        extraField;
    protected Integer       sort;
    protected Double        sizeMax;
    protected Long          sizeUse;
    protected Integer       status;
    protected LocalDateTime modifyTime;
    protected LocalDateTime createTime;
    protected Long          tenantId;

    public GroupsModel() {}

    public GroupsModel(GroupsModel value) {
        this.id = value.id;
        this.name = value.name;
        this.parentId = value.parentId;
        this.parentLevel = value.parentLevel;
        this.extraField = value.extraField;
        this.sort = value.sort;
        this.sizeMax = value.sizeMax;
        this.sizeUse = value.sizeUse;
        this.status = value.status;
        this.modifyTime = value.modifyTime;
        this.createTime = value.createTime;
        this.tenantId = value.tenantId;
    }

    public GroupsModel(
        Long          id,
        String        name,
        Long          parentId,
        String        parentLevel,
        String        extraField,
        Integer       sort,
        Double        sizeMax,
        Long          sizeUse,
        Integer       status,
        LocalDateTime modifyTime,
        LocalDateTime createTime,
        Long          tenantId
    ) {
        this.id = id;
        this.name = name;
        this.parentId = parentId;
        this.parentLevel = parentLevel;
        this.extraField = extraField;
        this.sort = sort;
        this.sizeMax = sizeMax;
        this.sizeUse = sizeUse;
        this.status = status;
        this.modifyTime = modifyTime;
        this.createTime = createTime;
        this.tenantId = tenantId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getParentId() {
        return this.parentId;
    }

    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    public String getParentLevel() {
        return this.parentLevel;
    }

    public void setParentLevel(String parentLevel) {
        this.parentLevel = parentLevel;
    }

    public String getExtraField() {
        return this.extraField;
    }

    public void setExtraField(String extraField) {
        this.extraField = extraField;
    }

    public Integer getSort() {
        return this.sort;
    }

    public void setSort(Integer sort) {
        this.sort = sort;
    }

    public Double getSizeMax() {
        return this.sizeMax;
    }

    public void setSizeMax(Double sizeMax) {
        this.sizeMax = sizeMax;
    }

    public Long getSizeUse() {
        return this.sizeUse;
    }

    public void setSizeUse(Long sizeUse) {
        this.sizeUse = sizeUse;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public LocalDateTime getModifyTime() {
        return this.modifyTime;
    }

    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public Long getTenantId() {
        return this.tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GroupsModel (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(parentId);
        sb.append(", ").append(parentLevel);
        sb.append(", ").append(extraField);
        sb.append(", ").append(sort);
        sb.append(", ").append(sizeMax);
        sb.append(", ").append(sizeUse);
        sb.append(", ").append(status);
        sb.append(", ").append(modifyTime);
        sb.append(", ").append(createTime);
        sb.append(", ").append(tenantId);

        sb.append(")");
        return sb.toString();
    }
}
