/*
 * This file is generated by jOOQ.
 */
package com.svnlan.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * 文件id
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IoFileContentsModel implements Serializable {

    private static final long serialVersionUID = -515024579;

    protected Long          fileId;
    protected String        content;
    protected LocalDateTime createTime;
    protected Long          tenantId;

    public IoFileContentsModel() {}

    public IoFileContentsModel(IoFileContentsModel value) {
        this.fileId = value.fileId;
        this.content = value.content;
        this.createTime = value.createTime;
        this.tenantId = value.tenantId;
    }

    public IoFileContentsModel(
        Long          fileId,
        String        content,
        LocalDateTime createTime,
        Long          tenantId
    ) {
        this.fileId = fileId;
        this.content = content;
        this.createTime = createTime;
        this.tenantId = tenantId;
    }

    public Long getFileId() {
        return this.fileId;
    }

    public void setFileId(Long fileId) {
        this.fileId = fileId;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public Long getTenantId() {
        return this.tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("IoFileContentsModel (");

        sb.append(fileId);
        sb.append(", ").append(content);
        sb.append(", ").append(createTime);
        sb.append(", ").append(tenantId);

        sb.append(")");
        return sb.toString();
    }
}
