/*
 * This file is generated by jOOQ.
 */
package com.svnlan.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * 任务执行记录表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LogScheduleModel implements Serializable {

    private static final long serialVersionUID = -1619304783;

    protected Long          id;
    protected String        commonScheduleId;
    protected LocalDateTime gmtStart;
    protected LocalDateTime gmtEnd;
    protected String        state;
    protected String        remark;
    protected Long          tenantId;

    public LogScheduleModel() {}

    public LogScheduleModel(LogScheduleModel value) {
        this.id = value.id;
        this.commonScheduleId = value.commonScheduleId;
        this.gmtStart = value.gmtStart;
        this.gmtEnd = value.gmtEnd;
        this.state = value.state;
        this.remark = value.remark;
        this.tenantId = value.tenantId;
    }

    public LogScheduleModel(
        Long          id,
        String        commonScheduleId,
        LocalDateTime gmtStart,
        LocalDateTime gmtEnd,
        String        state,
        String        remark,
        Long          tenantId
    ) {
        this.id = id;
        this.commonScheduleId = commonScheduleId;
        this.gmtStart = gmtStart;
        this.gmtEnd = gmtEnd;
        this.state = state;
        this.remark = remark;
        this.tenantId = tenantId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCommonScheduleId() {
        return this.commonScheduleId;
    }

    public void setCommonScheduleId(String commonScheduleId) {
        this.commonScheduleId = commonScheduleId;
    }

    public LocalDateTime getGmtStart() {
        return this.gmtStart;
    }

    public void setGmtStart(LocalDateTime gmtStart) {
        this.gmtStart = gmtStart;
    }

    public LocalDateTime getGmtEnd() {
        return this.gmtEnd;
    }

    public void setGmtEnd(LocalDateTime gmtEnd) {
        this.gmtEnd = gmtEnd;
    }

    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Long getTenantId() {
        return this.tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("LogScheduleModel (");

        sb.append(id);
        sb.append(", ").append(commonScheduleId);
        sb.append(", ").append(gmtStart);
        sb.append(", ").append(gmtEnd);
        sb.append(", ").append(state);
        sb.append(", ").append(remark);
        sb.append(", ").append(tenantId);

        sb.append(")");
        return sb.toString();
    }
}
