/*
 * This file is generated by jOOQ.
 */
package com.svnlan.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * 分享数据表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShareModel implements Serializable {

    private static final long serialVersionUID = 1755068374;

    protected Long          id;
    protected String        title;
    protected String        shareHash;
    protected Long          userId;
    protected Long          sourceId;
    protected String        sourcePath;
    protected String        url;
    protected Integer       isLink;
    protected Integer       status;
    protected Integer       isShareTo;
    protected String        password;
    protected Long          timeTo;
    protected Integer       numView;
    protected Integer       numDownload;
    protected String        options;
    protected LocalDateTime createTime;
    protected LocalDateTime modifyTime;
    protected Long          tenantId;

    public ShareModel() {}

    public ShareModel(ShareModel value) {
        this.id = value.id;
        this.title = value.title;
        this.shareHash = value.shareHash;
        this.userId = value.userId;
        this.sourceId = value.sourceId;
        this.sourcePath = value.sourcePath;
        this.url = value.url;
        this.isLink = value.isLink;
        this.status = value.status;
        this.isShareTo = value.isShareTo;
        this.password = value.password;
        this.timeTo = value.timeTo;
        this.numView = value.numView;
        this.numDownload = value.numDownload;
        this.options = value.options;
        this.createTime = value.createTime;
        this.modifyTime = value.modifyTime;
        this.tenantId = value.tenantId;
    }

    public ShareModel(
        Long          id,
        String        title,
        String        shareHash,
        Long          userId,
        Long          sourceId,
        String        sourcePath,
        String        url,
        Integer       isLink,
        Integer       status,
        Integer       isShareTo,
        String        password,
        Long          timeTo,
        Integer       numView,
        Integer       numDownload,
        String        options,
        LocalDateTime createTime,
        LocalDateTime modifyTime,
        Long          tenantId
    ) {
        this.id = id;
        this.title = title;
        this.shareHash = shareHash;
        this.userId = userId;
        this.sourceId = sourceId;
        this.sourcePath = sourcePath;
        this.url = url;
        this.isLink = isLink;
        this.status = status;
        this.isShareTo = isShareTo;
        this.password = password;
        this.timeTo = timeTo;
        this.numView = numView;
        this.numDownload = numDownload;
        this.options = options;
        this.createTime = createTime;
        this.modifyTime = modifyTime;
        this.tenantId = tenantId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getShareHash() {
        return this.shareHash;
    }

    public void setShareHash(String shareHash) {
        this.shareHash = shareHash;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getSourceId() {
        return this.sourceId;
    }

    public void setSourceId(Long sourceId) {
        this.sourceId = sourceId;
    }

    public String getSourcePath() {
        return this.sourcePath;
    }

    public void setSourcePath(String sourcePath) {
        this.sourcePath = sourcePath;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Integer getIsLink() {
        return this.isLink;
    }

    public void setIsLink(Integer isLink) {
        this.isLink = isLink;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getIsShareTo() {
        return this.isShareTo;
    }

    public void setIsShareTo(Integer isShareTo) {
        this.isShareTo = isShareTo;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Long getTimeTo() {
        return this.timeTo;
    }

    public void setTimeTo(Long timeTo) {
        this.timeTo = timeTo;
    }

    public Integer getNumView() {
        return this.numView;
    }

    public void setNumView(Integer numView) {
        this.numView = numView;
    }

    public Integer getNumDownload() {
        return this.numDownload;
    }

    public void setNumDownload(Integer numDownload) {
        this.numDownload = numDownload;
    }

    public String getOptions() {
        return this.options;
    }

    public void setOptions(String options) {
        this.options = options;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public LocalDateTime getModifyTime() {
        return this.modifyTime;
    }

    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    public Long getTenantId() {
        return this.tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ShareModel (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(shareHash);
        sb.append(", ").append(userId);
        sb.append(", ").append(sourceId);
        sb.append(", ").append(sourcePath);
        sb.append(", ").append(url);
        sb.append(", ").append(isLink);
        sb.append(", ").append(status);
        sb.append(", ").append(isShareTo);
        sb.append(", ").append(password);
        sb.append(", ").append(timeTo);
        sb.append(", ").append(numView);
        sb.append(", ").append(numDownload);
        sb.append(", ").append(options);
        sb.append(", ").append(createTime);
        sb.append(", ").append(modifyTime);
        sb.append(", ").append(tenantId);

        sb.append(")");
        return sb.toString();
    }
}
