/*
 * This file is generated by jOOQ.
 */
package com.svnlan.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * session
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SystemSessionModel implements Serializable {

    private static final long serialVersionUID = 2034167131;

    protected Integer       id;
    protected String        sign;
    protected Long          userId;
    protected String        content;
    protected Long          expires;
    protected LocalDateTime modifyTime;
    protected LocalDateTime createTime;
    protected Long          tenantId;

    public SystemSessionModel() {}

    public SystemSessionModel(SystemSessionModel value) {
        this.id = value.id;
        this.sign = value.sign;
        this.userId = value.userId;
        this.content = value.content;
        this.expires = value.expires;
        this.modifyTime = value.modifyTime;
        this.createTime = value.createTime;
        this.tenantId = value.tenantId;
    }

    public SystemSessionModel(
        Integer       id,
        String        sign,
        Long          userId,
        String        content,
        Long          expires,
        LocalDateTime modifyTime,
        LocalDateTime createTime,
        Long          tenantId
    ) {
        this.id = id;
        this.sign = sign;
        this.userId = userId;
        this.content = content;
        this.expires = expires;
        this.modifyTime = modifyTime;
        this.createTime = createTime;
        this.tenantId = tenantId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getSign() {
        return this.sign;
    }

    public void setSign(String sign) {
        this.sign = sign;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Long getExpires() {
        return this.expires;
    }

    public void setExpires(Long expires) {
        this.expires = expires;
    }

    public LocalDateTime getModifyTime() {
        return this.modifyTime;
    }

    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public Long getTenantId() {
        return this.tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SystemSessionModel (");

        sb.append(id);
        sb.append(", ").append(sign);
        sb.append(", ").append(userId);
        sb.append(", ").append(content);
        sb.append(", ").append(expires);
        sb.append(", ").append(modifyTime);
        sb.append(", ").append(createTime);
        sb.append(", ").append(tenantId);

        sb.append(")");
        return sb.toString();
    }
}
