/*
 * This file is generated by jOOQ.
 */
package com.svnlan.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * 用户表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersModel implements Serializable {

    private static final long serialVersionUID = -2104367981;

    protected Long          id;
    protected String        name;
    protected Integer       roleId;
    protected String        email;
    protected String        phone;
    protected String        nickname;
    protected String        avatar;
    protected Integer       sex;
    protected String        password;
    protected Double        sizeMax;
    protected Long          sizeUse;
    protected Integer       status;
    protected String        dingOpenId;
    protected String        wechatOpenId;
    protected String        enWechatOpenId;
    protected String        alipayOpenId;
    protected Integer       isSystem;
    protected LocalDateTime lastLogin;
    protected LocalDateTime createTime;
    protected LocalDateTime modifyTime;
    protected Long          tenantId;

    public UsersModel() {}

    public UsersModel(UsersModel value) {
        this.id = value.id;
        this.name = value.name;
        this.roleId = value.roleId;
        this.email = value.email;
        this.phone = value.phone;
        this.nickname = value.nickname;
        this.avatar = value.avatar;
        this.sex = value.sex;
        this.password = value.password;
        this.sizeMax = value.sizeMax;
        this.sizeUse = value.sizeUse;
        this.status = value.status;
        this.dingOpenId = value.dingOpenId;
        this.wechatOpenId = value.wechatOpenId;
        this.enWechatOpenId = value.enWechatOpenId;
        this.alipayOpenId = value.alipayOpenId;
        this.isSystem = value.isSystem;
        this.lastLogin = value.lastLogin;
        this.createTime = value.createTime;
        this.modifyTime = value.modifyTime;
        this.tenantId = value.tenantId;
    }

    public UsersModel(
        Long          id,
        String        name,
        Integer       roleId,
        String        email,
        String        phone,
        String        nickname,
        String        avatar,
        Integer       sex,
        String        password,
        Double        sizeMax,
        Long          sizeUse,
        Integer       status,
        String        dingOpenId,
        String        wechatOpenId,
        String        enWechatOpenId,
        String        alipayOpenId,
        Integer       isSystem,
        LocalDateTime lastLogin,
        LocalDateTime createTime,
        LocalDateTime modifyTime,
        Long          tenantId
    ) {
        this.id = id;
        this.name = name;
        this.roleId = roleId;
        this.email = email;
        this.phone = phone;
        this.nickname = nickname;
        this.avatar = avatar;
        this.sex = sex;
        this.password = password;
        this.sizeMax = sizeMax;
        this.sizeUse = sizeUse;
        this.status = status;
        this.dingOpenId = dingOpenId;
        this.wechatOpenId = wechatOpenId;
        this.enWechatOpenId = enWechatOpenId;
        this.alipayOpenId = alipayOpenId;
        this.isSystem = isSystem;
        this.lastLogin = lastLogin;
        this.createTime = createTime;
        this.modifyTime = modifyTime;
        this.tenantId = tenantId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getNickname() {
        return this.nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getAvatar() {
        return this.avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public Integer getSex() {
        return this.sex;
    }

    public void setSex(Integer sex) {
        this.sex = sex;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Double getSizeMax() {
        return this.sizeMax;
    }

    public void setSizeMax(Double sizeMax) {
        this.sizeMax = sizeMax;
    }

    public Long getSizeUse() {
        return this.sizeUse;
    }

    public void setSizeUse(Long sizeUse) {
        this.sizeUse = sizeUse;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getDingOpenId() {
        return this.dingOpenId;
    }

    public void setDingOpenId(String dingOpenId) {
        this.dingOpenId = dingOpenId;
    }

    public String getWechatOpenId() {
        return this.wechatOpenId;
    }

    public void setWechatOpenId(String wechatOpenId) {
        this.wechatOpenId = wechatOpenId;
    }

    public String getEnWechatOpenId() {
        return this.enWechatOpenId;
    }

    public void setEnWechatOpenId(String enWechatOpenId) {
        this.enWechatOpenId = enWechatOpenId;
    }

    public String getAlipayOpenId() {
        return this.alipayOpenId;
    }

    public void setAlipayOpenId(String alipayOpenId) {
        this.alipayOpenId = alipayOpenId;
    }

    public Integer getIsSystem() {
        return this.isSystem;
    }

    public void setIsSystem(Integer isSystem) {
        this.isSystem = isSystem;
    }

    public LocalDateTime getLastLogin() {
        return this.lastLogin;
    }

    public void setLastLogin(LocalDateTime lastLogin) {
        this.lastLogin = lastLogin;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public LocalDateTime getModifyTime() {
        return this.modifyTime;
    }

    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    public Long getTenantId() {
        return this.tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UsersModel (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(roleId);
        sb.append(", ").append(email);
        sb.append(", ").append(phone);
        sb.append(", ").append(nickname);
        sb.append(", ").append(avatar);
        sb.append(", ").append(sex);
        sb.append(", ").append(password);
        sb.append(", ").append(sizeMax);
        sb.append(", ").append(sizeUse);
        sb.append(", ").append(status);
        sb.append(", ").append(dingOpenId);
        sb.append(", ").append(wechatOpenId);
        sb.append(", ").append(enWechatOpenId);
        sb.append(", ").append(alipayOpenId);
        sb.append(", ").append(isSystem);
        sb.append(", ").append(lastLogin);
        sb.append(", ").append(createTime);
        sb.append(", ").append(modifyTime);
        sb.append(", ").append(tenantId);

        sb.append(")");
        return sb.toString();
    }
}
