/*
 * This file is generated by jOOQ.
 */
package com.svnlan.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * 用户资讯表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserCommonInfoModel implements Serializable {

    private static final long serialVersionUID = -748471087;

    protected Long          id;
    protected Long          userId;
    protected Long          infoId;
    protected String        ip;
    protected Integer       viewCount;
    protected Integer       isLike;
    protected LocalDateTime createTime;
    protected LocalDateTime modifyTime;
    protected Long          tenantId;

    public UserCommonInfoModel() {}

    public UserCommonInfoModel(UserCommonInfoModel value) {
        this.id = value.id;
        this.userId = value.userId;
        this.infoId = value.infoId;
        this.ip = value.ip;
        this.viewCount = value.viewCount;
        this.isLike = value.isLike;
        this.createTime = value.createTime;
        this.modifyTime = value.modifyTime;
        this.tenantId = value.tenantId;
    }

    public UserCommonInfoModel(
        Long          id,
        Long          userId,
        Long          infoId,
        String        ip,
        Integer       viewCount,
        Integer       isLike,
        LocalDateTime createTime,
        LocalDateTime modifyTime,
        Long          tenantId
    ) {
        this.id = id;
        this.userId = userId;
        this.infoId = infoId;
        this.ip = ip;
        this.viewCount = viewCount;
        this.isLike = isLike;
        this.createTime = createTime;
        this.modifyTime = modifyTime;
        this.tenantId = tenantId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getInfoId() {
        return this.infoId;
    }

    public void setInfoId(Long infoId) {
        this.infoId = infoId;
    }

    public String getIp() {
        return this.ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    public Integer getViewCount() {
        return this.viewCount;
    }

    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    public Integer getIsLike() {
        return this.isLike;
    }

    public void setIsLike(Integer isLike) {
        this.isLike = isLike;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public LocalDateTime getModifyTime() {
        return this.modifyTime;
    }

    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    public Long getTenantId() {
        return this.tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserCommonInfoModel (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(infoId);
        sb.append(", ").append(ip);
        sb.append(", ").append(viewCount);
        sb.append(", ").append(isLike);
        sb.append(", ").append(createTime);
        sb.append(", ").append(modifyTime);
        sb.append(", ").append(tenantId);

        sb.append(")");
        return sb.toString();
    }
}
