/*
 * This file is generated by jOOQ.
 */
package com.svnlan.jooq.tables.daos;


import com.svnlan.jooq.tables.SystemOption;
import com.svnlan.jooq.tables.pojos.SystemOptionModel;
import com.svnlan.jooq.tables.records.SystemOptionRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 系统配置表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SystemOptionDao extends DAOImpl<SystemOptionRecord, SystemOptionModel, Integer> {

    /**
     * Create a new SystemOptionDao without any configuration
     */
    public SystemOptionDao() {
        super(SystemOption.SYSTEM_OPTION, SystemOptionModel.class);
    }

    /**
     * Create a new SystemOptionDao with an attached configuration
     */
    public SystemOptionDao(Configuration configuration) {
        super(SystemOption.SYSTEM_OPTION, SystemOptionModel.class, configuration);
    }

    @Override
    public Integer getId(SystemOptionModel object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<SystemOptionModel> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(SystemOption.SYSTEM_OPTION.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<SystemOptionModel> fetchById(Integer... values) {
        return fetch(SystemOption.SYSTEM_OPTION.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public SystemOptionModel fetchOneById(Integer value) {
        return fetchOne(SystemOption.SYSTEM_OPTION.ID, value);
    }

    /**
     * Fetch records that have <code>type BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<SystemOptionModel> fetchRangeOfType(String lowerInclusive, String upperInclusive) {
        return fetchRange(SystemOption.SYSTEM_OPTION.TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<SystemOptionModel> fetchByType(String... values) {
        return fetch(SystemOption.SYSTEM_OPTION.TYPE, values);
    }

    /**
     * Fetch records that have <code>key_string BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<SystemOptionModel> fetchRangeOfKeyString(String lowerInclusive, String upperInclusive) {
        return fetchRange(SystemOption.SYSTEM_OPTION.KEY_STRING, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>key_string IN (values)</code>
     */
    public List<SystemOptionModel> fetchByKeyString(String... values) {
        return fetch(SystemOption.SYSTEM_OPTION.KEY_STRING, values);
    }

    /**
     * Fetch records that have <code>value_text BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<SystemOptionModel> fetchRangeOfValueText(String lowerInclusive, String upperInclusive) {
        return fetchRange(SystemOption.SYSTEM_OPTION.VALUE_TEXT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>value_text IN (values)</code>
     */
    public List<SystemOptionModel> fetchByValueText(String... values) {
        return fetch(SystemOption.SYSTEM_OPTION.VALUE_TEXT, values);
    }

    /**
     * Fetch records that have <code>create_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<SystemOptionModel> fetchRangeOfCreateTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(SystemOption.SYSTEM_OPTION.CREATE_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<SystemOptionModel> fetchByCreateTime(LocalDateTime... values) {
        return fetch(SystemOption.SYSTEM_OPTION.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>modify_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<SystemOptionModel> fetchRangeOfModifyTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(SystemOption.SYSTEM_OPTION.MODIFY_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>modify_time IN (values)</code>
     */
    public List<SystemOptionModel> fetchByModifyTime(LocalDateTime... values) {
        return fetch(SystemOption.SYSTEM_OPTION.MODIFY_TIME, values);
    }

    /**
     * Fetch records that have <code>tenant_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<SystemOptionModel> fetchRangeOfTenantId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(SystemOption.SYSTEM_OPTION.TENANT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>tenant_id IN (values)</code>
     */
    public List<SystemOptionModel> fetchByTenantId(Long... values) {
        return fetch(SystemOption.SYSTEM_OPTION.TENANT_ID, values);
    }
}
