/*
 * This file is generated by jOOQ.
 */
package com.svnlan.jooq;


import com.svnlan.jooq.tables.Comment;
import com.svnlan.jooq.tables.CommentMeta;
import com.svnlan.jooq.tables.CommentPraise;
import com.svnlan.jooq.tables.CommonConvert;
import com.svnlan.jooq.tables.CommonDesign;
import com.svnlan.jooq.tables.CommonDesignClassify;
import com.svnlan.jooq.tables.CommonInfo;
import com.svnlan.jooq.tables.CommonInfoType;
import com.svnlan.jooq.tables.CommonLabel;
import com.svnlan.jooq.tables.CommonSchedule;
import com.svnlan.jooq.tables.Databasechangelog;
import com.svnlan.jooq.tables.Databasechangeloglock;
import com.svnlan.jooq.tables.GroupMeta;
import com.svnlan.jooq.tables.GroupSource;
import com.svnlan.jooq.tables.Groups;
import com.svnlan.jooq.tables.IoFile;
import com.svnlan.jooq.tables.IoFileContents;
import com.svnlan.jooq.tables.IoFileMeta;
import com.svnlan.jooq.tables.IoSource;
import com.svnlan.jooq.tables.IoSourceAuth;
import com.svnlan.jooq.tables.IoSourceEvent;
import com.svnlan.jooq.tables.IoSourceHistory;
import com.svnlan.jooq.tables.IoSourceMeta;
import com.svnlan.jooq.tables.IoSourceRecycle;
import com.svnlan.jooq.tables.LogSchedule;
import com.svnlan.jooq.tables.Notice;
import com.svnlan.jooq.tables.NoticeDetail;
import com.svnlan.jooq.tables.NoticeUser;
import com.svnlan.jooq.tables.Role;
import com.svnlan.jooq.tables.Share;
import com.svnlan.jooq.tables.ShareReport;
import com.svnlan.jooq.tables.ShareTo;
import com.svnlan.jooq.tables.SystemLog;
import com.svnlan.jooq.tables.SystemOption;
import com.svnlan.jooq.tables.SystemSession;
import com.svnlan.jooq.tables.TTenant;
import com.svnlan.jooq.tables.UserCommonInfo;
import com.svnlan.jooq.tables.UserFav;
import com.svnlan.jooq.tables.UserGroup;
import com.svnlan.jooq.tables.UserMeta;
import com.svnlan.jooq.tables.UserOption;
import com.svnlan.jooq.tables.Users;
import com.svnlan.jooq.tables.VisitCountRecord;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CloudDisk extends SchemaImpl {

    private static final long serialVersionUID = 1792984652;

    /**
     * The reference instance of <code>cloud_disk</code>
     */
    public static final CloudDisk CLOUD_DISK = new CloudDisk();

    /**
     * 通用评论表
     */
    public final Comment COMMENT = com.svnlan.jooq.tables.Comment.COMMENT;

    /**
     * 评论表扩展字段
     */
    public final CommentMeta COMMENT_META = com.svnlan.jooq.tables.CommentMeta.COMMENT_META;

    /**
     * 评论点赞表
     */
    public final CommentPraise COMMENT_PRAISE = com.svnlan.jooq.tables.CommentPraise.COMMENT_PRAISE;

    /**
     * 转码表
     */
    public final CommonConvert COMMON_CONVERT = com.svnlan.jooq.tables.CommonConvert.COMMON_CONVERT;

    /**
     * 页面编辑器表
     */
    public final CommonDesign COMMON_DESIGN = com.svnlan.jooq.tables.CommonDesign.COMMON_DESIGN;

    /**
     * 装扮目录分类表
     */
    public final CommonDesignClassify COMMON_DESIGN_CLASSIFY = com.svnlan.jooq.tables.CommonDesignClassify.COMMON_DESIGN_CLASSIFY;

    /**
     * 资讯表
     */
    public final CommonInfo COMMON_INFO = com.svnlan.jooq.tables.CommonInfo.COMMON_INFO;

    /**
     * 资讯类型表
     */
    public final CommonInfoType COMMON_INFO_TYPE = com.svnlan.jooq.tables.CommonInfoType.COMMON_INFO_TYPE;

    /**
     * 标签表
     */
    public final CommonLabel COMMON_LABEL = com.svnlan.jooq.tables.CommonLabel.COMMON_LABEL;

    /**
     * 定时任务表
     */
    public final CommonSchedule COMMON_SCHEDULE = com.svnlan.jooq.tables.CommonSchedule.COMMON_SCHEDULE;

    /**
     * The table <code>cloud_disk.databasechangelog</code>.
     */
    public final Databasechangelog DATABASECHANGELOG = com.svnlan.jooq.tables.Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>cloud_disk.databasechangeloglock</code>.
     */
    public final Databasechangeloglock DATABASECHANGELOGLOCK = com.svnlan.jooq.tables.Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * 用户数据扩展表
     */
    public final GroupMeta GROUP_META = com.svnlan.jooq.tables.GroupMeta.GROUP_META;

    /**
     * 群组、文件关系表
     */
    public final GroupSource GROUP_SOURCE = com.svnlan.jooq.tables.GroupSource.GROUP_SOURCE;

    /**
     * 群组表
     */
    public final Groups GROUPS = com.svnlan.jooq.tables.Groups.GROUPS;

    /**
     * 文档存储表
     */
    public final IoFile IO_FILE = com.svnlan.jooq.tables.IoFile.IO_FILE;

    /**
     * 文件id
     */
    public final IoFileContents IO_FILE_CONTENTS = com.svnlan.jooq.tables.IoFileContents.IO_FILE_CONTENTS;

    /**
     * 文件扩展表
     */
    public final IoFileMeta IO_FILE_META = com.svnlan.jooq.tables.IoFileMeta.IO_FILE_META;

    /**
     * 文档数据表
     */
    public final IoSource IO_SOURCE = com.svnlan.jooq.tables.IoSource.IO_SOURCE;

    /**
     * 文档权限表
     */
    public final IoSourceAuth IO_SOURCE_AUTH = com.svnlan.jooq.tables.IoSourceAuth.IO_SOURCE_AUTH;

    /**
     * 文档事件表
     */
    public final IoSourceEvent IO_SOURCE_EVENT = com.svnlan.jooq.tables.IoSourceEvent.IO_SOURCE_EVENT;

    /**
     * 文档历史记录表
     */
    public final IoSourceHistory IO_SOURCE_HISTORY = com.svnlan.jooq.tables.IoSourceHistory.IO_SOURCE_HISTORY;

    /**
     * 文档扩展表
     */
    public final IoSourceMeta IO_SOURCE_META = com.svnlan.jooq.tables.IoSourceMeta.IO_SOURCE_META;

    /**
     * 文档回收站
     */
    public final IoSourceRecycle IO_SOURCE_RECYCLE = com.svnlan.jooq.tables.IoSourceRecycle.IO_SOURCE_RECYCLE;

    /**
     * 任务执行记录表
     */
    public final LogSchedule LOG_SCHEDULE = com.svnlan.jooq.tables.LogSchedule.LOG_SCHEDULE;

    /**
     * 通知表
     */
    public final Notice NOTICE = com.svnlan.jooq.tables.Notice.NOTICE;

    /**
     * 通知详情表
     */
    public final NoticeDetail NOTICE_DETAIL = com.svnlan.jooq.tables.NoticeDetail.NOTICE_DETAIL;

    /**
     * 通知用户关联表
     */
    public final NoticeUser NOTICE_USER = com.svnlan.jooq.tables.NoticeUser.NOTICE_USER;

    /**
     * 角色表
     */
    public final Role ROLE = com.svnlan.jooq.tables.Role.ROLE;

    /**
     * 分享数据表
     */
    public final Share SHARE = com.svnlan.jooq.tables.Share.SHARE;

    /**
     * 分享举报表
     */
    public final ShareReport SHARE_REPORT = com.svnlan.jooq.tables.ShareReport.SHARE_REPORT;

    /**
     * 分享给指定用户(协作)
     */
    public final ShareTo SHARE_TO = com.svnlan.jooq.tables.ShareTo.SHARE_TO;

    /**
     * 系统日志表
     */
    public final SystemLog SYSTEM_LOG = com.svnlan.jooq.tables.SystemLog.SYSTEM_LOG;

    /**
     * 系统配置表
     */
    public final SystemOption SYSTEM_OPTION = com.svnlan.jooq.tables.SystemOption.SYSTEM_OPTION;

    /**
     * session
     */
    public final SystemSession SYSTEM_SESSION = com.svnlan.jooq.tables.SystemSession.SYSTEM_SESSION;

    /**
     * 租户表
     */
    public final TTenant T_TENANT = com.svnlan.jooq.tables.TTenant.T_TENANT;

    /**
     * 用户资讯表
     */
    public final UserCommonInfo USER_COMMON_INFO = com.svnlan.jooq.tables.UserCommonInfo.USER_COMMON_INFO;

    /**
     * 用户文档标签表
     */
    public final UserFav USER_FAV = com.svnlan.jooq.tables.UserFav.USER_FAV;

    /**
     * 用户群组关联表(一对多)
     */
    public final UserGroup USER_GROUP = com.svnlan.jooq.tables.UserGroup.USER_GROUP;

    /**
     * 用户数据扩展表
     */
    public final UserMeta USER_META = com.svnlan.jooq.tables.UserMeta.USER_META;

    /**
     * 用户数据配置表
     */
    public final UserOption USER_OPTION = com.svnlan.jooq.tables.UserOption.USER_OPTION;

    /**
     * 用户表
     */
    public final Users USERS = com.svnlan.jooq.tables.Users.USERS;

    /**
     * 访问次数记录表
     */
    public final VisitCountRecord VISIT_COUNT_RECORD = com.svnlan.jooq.tables.VisitCountRecord.VISIT_COUNT_RECORD;

    /**
     * No further instances allowed
     */
    private CloudDisk() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Comment.COMMENT,
            CommentMeta.COMMENT_META,
            CommentPraise.COMMENT_PRAISE,
            CommonConvert.COMMON_CONVERT,
            CommonDesign.COMMON_DESIGN,
            CommonDesignClassify.COMMON_DESIGN_CLASSIFY,
            CommonInfo.COMMON_INFO,
            CommonInfoType.COMMON_INFO_TYPE,
            CommonLabel.COMMON_LABEL,
            CommonSchedule.COMMON_SCHEDULE,
            Databasechangelog.DATABASECHANGELOG,
            Databasechangeloglock.DATABASECHANGELOGLOCK,
            GroupMeta.GROUP_META,
            GroupSource.GROUP_SOURCE,
            Groups.GROUPS,
            IoFile.IO_FILE,
            IoFileContents.IO_FILE_CONTENTS,
            IoFileMeta.IO_FILE_META,
            IoSource.IO_SOURCE,
            IoSourceAuth.IO_SOURCE_AUTH,
            IoSourceEvent.IO_SOURCE_EVENT,
            IoSourceHistory.IO_SOURCE_HISTORY,
            IoSourceMeta.IO_SOURCE_META,
            IoSourceRecycle.IO_SOURCE_RECYCLE,
            LogSchedule.LOG_SCHEDULE,
            Notice.NOTICE,
            NoticeDetail.NOTICE_DETAIL,
            NoticeUser.NOTICE_USER,
            Role.ROLE,
            Share.SHARE,
            ShareReport.SHARE_REPORT,
            ShareTo.SHARE_TO,
            SystemLog.SYSTEM_LOG,
            SystemOption.SYSTEM_OPTION,
            SystemSession.SYSTEM_SESSION,
            TTenant.T_TENANT,
            UserCommonInfo.USER_COMMON_INFO,
            UserFav.USER_FAV,
            UserGroup.USER_GROUP,
            UserMeta.USER_META,
            UserOption.USER_OPTION,
            Users.USERS,
            VisitCountRecord.VISIT_COUNT_RECORD);
    }
}
