/*
 * This file is generated by jOOQ.
 */
package com.svnlan.jooq.tables;


import com.svnlan.jooq.CloudDisk;
import com.svnlan.jooq.Indexes;
import com.svnlan.jooq.Keys;
import com.svnlan.jooq.tables.records.GroupMetaRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 用户数据扩展表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupMeta extends TableImpl<GroupMetaRecord> {

    private static final long serialVersionUID = -977906166;

    /**
     * The reference instance of <code>cloud_disk.group_meta</code>
     */
    public static final GroupMeta GROUP_META = new GroupMeta();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GroupMetaRecord> getRecordType() {
        return GroupMetaRecord.class;
    }

    /**
     * The column <code>cloud_disk.group_meta.id</code>.
     */
    public final TableField<GroupMetaRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>cloud_disk.group_meta.group_id</code>. 部门id
     */
    public final TableField<GroupMetaRecord, Long> GROUP_ID = createField(DSL.name("group_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "部门id");

    /**
     * The column <code>cloud_disk.group_meta.key_string</code>. 存储key
     */
    public final TableField<GroupMetaRecord, String> KEY_STRING = createField(DSL.name("key_string"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "存储key");

    /**
     * The column <code>cloud_disk.group_meta.value_text</code>. 对应值
     */
    public final TableField<GroupMetaRecord, String> VALUE_TEXT = createField(DSL.name("value_text"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "对应值");

    /**
     * The column <code>cloud_disk.group_meta.create_time</code>. 创建时间
     */
    public final TableField<GroupMetaRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "创建时间");

    /**
     * The column <code>cloud_disk.group_meta.modify_time</code>. 最后修改时间
     */
    public final TableField<GroupMetaRecord, LocalDateTime> MODIFY_TIME = createField(DSL.name("modify_time"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "最后修改时间");

    /**
     * The column <code>cloud_disk.group_meta.tenant_id</code>. 租户id
     */
    public final TableField<GroupMetaRecord, Long> TENANT_ID = createField(DSL.name("tenant_id"), org.jooq.impl.SQLDataType.BIGINT, this, "租户id");

    /**
     * Create a <code>cloud_disk.group_meta</code> table reference
     */
    public GroupMeta() {
        this(DSL.name("group_meta"), null);
    }

    /**
     * Create an aliased <code>cloud_disk.group_meta</code> table reference
     */
    public GroupMeta(String alias) {
        this(DSL.name(alias), GROUP_META);
    }

    /**
     * Create an aliased <code>cloud_disk.group_meta</code> table reference
     */
    public GroupMeta(Name alias) {
        this(alias, GROUP_META);
    }

    private GroupMeta(Name alias, Table<GroupMetaRecord> aliased) {
        this(alias, aliased, null);
    }

    private GroupMeta(Name alias, Table<GroupMetaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("用户数据扩展表"));
    }

    public <O extends Record> GroupMeta(Table<O> child, ForeignKey<O, GroupMetaRecord> key) {
        super(child, key, GROUP_META);
    }

    @Override
    public Schema getSchema() {
        return CloudDisk.CLOUD_DISK;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.GROUP_META_GROUP_META_KEYS, Indexes.GROUP_META_GROUPID_KEY, Indexes.GROUP_META_PRIMARY);
    }

    @Override
    public Identity<GroupMetaRecord, Long> getIdentity() {
        return Keys.IDENTITY_GROUP_META;
    }

    @Override
    public UniqueKey<GroupMetaRecord> getPrimaryKey() {
        return Keys.KEY_GROUP_META_PRIMARY;
    }

    @Override
    public List<UniqueKey<GroupMetaRecord>> getKeys() {
        return Arrays.<UniqueKey<GroupMetaRecord>>asList(Keys.KEY_GROUP_META_PRIMARY, Keys.KEY_GROUP_META_GROUPID_KEY);
    }

    @Override
    public GroupMeta as(String alias) {
        return new GroupMeta(DSL.name(alias), this);
    }

    @Override
    public GroupMeta as(Name alias) {
        return new GroupMeta(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public GroupMeta rename(String name) {
        return new GroupMeta(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GroupMeta rename(Name name) {
        return new GroupMeta(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Long, String, String, LocalDateTime, LocalDateTime, Long> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
