/*
 * This file is generated by jOOQ.
 */
package com.svnlan.jooq.tables;


import com.svnlan.jooq.CloudDisk;
import com.svnlan.jooq.Indexes;
import com.svnlan.jooq.Keys;
import com.svnlan.jooq.tables.records.IoSourceMetaRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 文档扩展表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IoSourceMeta extends TableImpl<IoSourceMetaRecord> {

    private static final long serialVersionUID = -1256721130;

    /**
     * The reference instance of <code>cloud_disk.io_source_meta</code>
     */
    public static final IoSourceMeta IO_SOURCE_META = new IoSourceMeta();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IoSourceMetaRecord> getRecordType() {
        return IoSourceMetaRecord.class;
    }

    /**
     * The column <code>cloud_disk.io_source_meta.id</code>.
     */
    public final TableField<IoSourceMetaRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>cloud_disk.io_source_meta.source_id</code>. 文档id
     */
    public final TableField<IoSourceMetaRecord, Long> SOURCE_ID = createField(DSL.name("source_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "文档id");

    /**
     * The column <code>cloud_disk.io_source_meta.key_string</code>. 存储key
     */
    public final TableField<IoSourceMetaRecord, String> KEY_STRING = createField(DSL.name("key_string"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "存储key");

    /**
     * The column <code>cloud_disk.io_source_meta.value_text</code>. 对应值
     */
    public final TableField<IoSourceMetaRecord, String> VALUE_TEXT = createField(DSL.name("value_text"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "对应值");

    /**
     * The column <code>cloud_disk.io_source_meta.create_time</code>. 创建时间
     */
    public final TableField<IoSourceMetaRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "创建时间");

    /**
     * The column <code>cloud_disk.io_source_meta.modify_time</code>. 最后修改时间
     */
    public final TableField<IoSourceMetaRecord, LocalDateTime> MODIFY_TIME = createField(DSL.name("modify_time"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "最后修改时间");

    /**
     * The column <code>cloud_disk.io_source_meta.tenant_id</code>. 租户id
     */
    public final TableField<IoSourceMetaRecord, Long> TENANT_ID = createField(DSL.name("tenant_id"), org.jooq.impl.SQLDataType.BIGINT, this, "租户id");

    /**
     * Create a <code>cloud_disk.io_source_meta</code> table reference
     */
    public IoSourceMeta() {
        this(DSL.name("io_source_meta"), null);
    }

    /**
     * Create an aliased <code>cloud_disk.io_source_meta</code> table reference
     */
    public IoSourceMeta(String alias) {
        this(DSL.name(alias), IO_SOURCE_META);
    }

    /**
     * Create an aliased <code>cloud_disk.io_source_meta</code> table reference
     */
    public IoSourceMeta(Name alias) {
        this(alias, IO_SOURCE_META);
    }

    private IoSourceMeta(Name alias, Table<IoSourceMetaRecord> aliased) {
        this(alias, aliased, null);
    }

    private IoSourceMeta(Name alias, Table<IoSourceMetaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("文档扩展表"));
    }

    public <O extends Record> IoSourceMeta(Table<O> child, ForeignKey<O, IoSourceMetaRecord> key) {
        super(child, key, IO_SOURCE_META);
    }

    @Override
    public Schema getSchema() {
        return CloudDisk.CLOUD_DISK;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.IO_SOURCE_META_IO_SOURCE_META_KEYS, Indexes.IO_SOURCE_META_PRIMARY, Indexes.IO_SOURCE_META_SOURCEID_KEY);
    }

    @Override
    public Identity<IoSourceMetaRecord, Long> getIdentity() {
        return Keys.IDENTITY_IO_SOURCE_META;
    }

    @Override
    public UniqueKey<IoSourceMetaRecord> getPrimaryKey() {
        return Keys.KEY_IO_SOURCE_META_PRIMARY;
    }

    @Override
    public List<UniqueKey<IoSourceMetaRecord>> getKeys() {
        return Arrays.<UniqueKey<IoSourceMetaRecord>>asList(Keys.KEY_IO_SOURCE_META_PRIMARY, Keys.KEY_IO_SOURCE_META_SOURCEID_KEY);
    }

    @Override
    public IoSourceMeta as(String alias) {
        return new IoSourceMeta(DSL.name(alias), this);
    }

    @Override
    public IoSourceMeta as(Name alias) {
        return new IoSourceMeta(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public IoSourceMeta rename(String name) {
        return new IoSourceMeta(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IoSourceMeta rename(Name name) {
        return new IoSourceMeta(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Long, String, String, LocalDateTime, LocalDateTime, Long> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
